CREATE TABLE [people].[PERSON]
(
	[P_ID] INT NOT NULL IDENTITY(1, 1),
	[P_GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[P_L_NAME] NVARCHAR(50) NOT NULL, 
    [P_F_NAME] NVARCHAR(50) NOT NULL, 
	[P_COUNTRY_CODE] CHAR(2) NOT NULL, 
	[P_PROVINCE] NVARCHAR(50) NOT NULL,
	[P_LOCATION] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK_PERSON] PRIMARY KEY ([P_ID]), 
    CONSTRAINT [AK_PERSON] UNIQUE ([P_GUID]), 
    CONSTRAINT [FK_PERSON_TO_LOCATION] FOREIGN KEY ([P_COUNTRY_CODE], [P_PROVINCE], [P_LOCATION]) REFERENCES [dimensions].[LOCATION]([L_COUNTRY_CODE], [L_PROVINCE], [L_NAME]), 


)

GO

CREATE INDEX [IX_PERSON_P_L_NAME] ON [people].[PERSON] ([P_L_NAME])

GO

CREATE INDEX [IX_PERSON_P_F_NAME] ON [people].[PERSON] ([P_F_NAME])

GO

CREATE INDEX [IX_PERSON_P_COUNTRY_CODE] ON [people].[PERSON] ([P_COUNTRY_CODE])

GO

CREATE INDEX [IX_PERSON_P_PROVINCE] ON [people].[PERSON] ([P_PROVINCE])

GO

CREATE INDEX [IX_PERSON_P_LOCATION] ON [people].[PERSON] ([P_LOCATION])

GO

CREATE INDEX [IX_PERSON_P_LOCATION_2] ON [people].[PERSON] ([P_COUNTRY_CODE], [P_PROVINCE], [P_LOCATION])
