CREATE TABLE [dimensions].[REGION_DETAIL]
(
	[RD_ID] INT IDENTITY(1, 1),
	[RD_COUNTRY_CODE] CHAR(2) NOT NULL, 
	[RD_NATIVE_NAME] NVARCHAR(50) NOT NULL, 
	[RD_DISPLAY_NAME] NVARCHAR(50) NOT NULL, 
	[RD_IS_METRIC] BIT NOT NULL, 
	[RD_COUNTRY_CODE_3] CHAR(3) NOT NULL, 
    CONSTRAINT [PK_REGION_DETAIL] PRIMARY KEY ([RD_ID]), 
    CONSTRAINT [FK_REGION_DETAIL_TO_REGION] FOREIGN KEY ([RD_COUNTRY_CODE]) REFERENCES [dimensions].[REGION]([R_COUNTRY_CODE]), 
    CONSTRAINT [AK_REGION_DETAIL] UNIQUE ([RD_COUNTRY_CODE], [RD_NATIVE_NAME], [RD_DISPLAY_NAME], [RD_IS_METRIC], [RD_COUNTRY_CODE_3]), 
)

GO

CREATE INDEX [IX_REGION_DETAIL_RD_COUNTRY_CODE] ON [dimensions].[REGION_DETAIL] ([RD_COUNTRY_CODE])

GO

CREATE INDEX [IX_REGION_DETAIL_RD_NATIVE_NAME] ON [dimensions].[REGION_DETAIL] ([RD_NATIVE_NAME])

GO

CREATE INDEX [IX_REGION_DETAIL_RD_DISPLAY_NAME] ON [dimensions].[REGION_DETAIL] ([RD_DISPLAY_NAME])

GO

CREATE INDEX [IX_REGION_DETAIL_RD_IS_METRIC] ON [dimensions].[REGION_DETAIL] ([RD_IS_METRIC])

GO

CREATE INDEX [IX_REGION_DETAIL_RD_COUNTRY_CODE_3] ON [dimensions].[REGION_DETAIL] ([RD_COUNTRY_CODE_3])
