CREATE TABLE [dimensions].[SURNAME]
(
	[SN_ID] INT IDENTITY(1, 1) NOT NULL,
	[SN_COUNTRY_CODE] CHAR(2) NOT NULL, 
    [SN_NAME] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK_SURNAME] PRIMARY KEY ([SN_ID]), 
    CONSTRAINT [AK_SURNAME] UNIQUE ([SN_COUNTRY_CODE], [SN_NAME]), 
    CONSTRAINT [FK_SURNAME_TO_REGION] FOREIGN KEY ([SN_COUNTRY_CODE]) REFERENCES [dimensions].[REGION]([R_COUNTRY_CODE]) 
)

GO

CREATE INDEX [IX_SURNAME_SN_COUNTRY_CODE] ON [dimensions].[SURNAME] ([SN_COUNTRY_CODE])

GO

CREATE INDEX [IX_SURNAME_SN_NAME] ON [dimensions].[SURNAME] ([SN_NAME])
