CREATE TABLE [dimensions].[REGION]
(
	[R_COUNTRY_CODE] CHAR(2) NOT NULL, 
	[R_ENGLISH_NAME] VARCHAR(50) NOT NULL, 
	[R_GEO_ID] INT NOT NULL, 
    [R_POPULATION] INT NOT NULL, 
    CONSTRAINT [PK_REGION] PRIMARY KEY ([R_COUNTRY_CODE]), 
    CONSTRAINT [CK_REGION_R_GEO_ID] CHECK ([R_GEO_ID] > 0), 
    CONSTRAINT [CK_REGION_R_POPULATION] CHECK ([R_POPULATION] >= 0), 
)

GO

CREATE INDEX [IX_REGION_R_POPULATION] ON [dimensions].[REGION] ([R_POPULATION])

GO

CREATE UNIQUE INDEX [UIX_REGION_R_ENGLISH_NAME] ON [dimensions].[REGION] ([R_ENGLISH_NAME])

GO

CREATE UNIQUE INDEX [UIX_REGION_R_GEO_ID] ON [dimensions].[REGION] ([R_GEO_ID])
