PRINT N'Merging into [dimensions].[LOCATION] ...';

MERGE INTO [dimensions].[LOCATION] AS [target] USING 
(VALUES 
	 ('AU', N'Adelaide', N'South Australia', 5.38) 
	,('AU', N'Albany', N'Western Australia', 0.14) 
	,('AU', N'Albury-Wodonga', N'New South Wales', 0.19) 
	,('AU', N'Albury-Wodonga', N'Victoria', 0.18) 
	,('AU', N'Alice Springs', N'Northern Territory', 0.11) 
	,('AU', N'Armidale', N'New South Wales', 0.1) 
	,('AU', N'Bacchus Marsh', N'Victoria', 0.09) 
	,('AU', N'Bairnsdale', N'Victoria', 0.06) 
	,('AU', N'Ballarat', N'Victoria', 0.42) 
	,('AU', N'Ballina', N'New South Wales', 0.11) 
	,('AU', N'Batemans Bay', N'New South Wales', 0.07) 
	,('AU', N'Bathurst', N'New South Wales', 0.15) 
	,('AU', N'Bendigo', N'Victoria', 0.4) 
	,('AU', N'Bowral-Mittagong', N'New South Wales', 0.16) 
	,('AU', N'Brisbane', N'Queensland', 9.85) 
	,('AU', N'Broken Hill', N'New South Wales', 0.07) 
	,('AU', N'Broome', N'Western Australia', 0.06) 
	,('AU', N'Bunbury', N'Western Australia', 0.3) 
	,('AU', N'Bundaberg', N'Queensland', 0.28) 
	,('AU', N'Burnie-Wynyard', N'Tasmania', 0.11) 
	,('AU', N'Busselton', N'Western Australia', 0.16) 
	,('AU', N'Cairns', N'Queensland', 0.61) 
	,('AU', N'Camden Haven', N'New South Wales', 0.07) 
	,('AU', N'Canberra-Queanbeyan', N'Australian Capital Territory', 0.92) 
	,('AU', N'Canberra-Queanbeyan', N'New South Wales', 0.91) 
	,('AU', N'Central Coast', N'New South Wales', 1.31) 
	,('AU', N'Coffs Harbour', N'New South Wales', 0.29) 
	,('AU', N'Colac', N'Victoria', 0.05) 
	,('AU', N'Darwin', N'Northern Territory', 0.59) 
	,('AU', N'Devonport', N'Tasmania', 0.12) 
	,('AU', N'Dubbo', N'New South Wales', 0.15) 
	,('AU', N'Echuca-Moama', N'Victoria', 0.04) 
	,('AU', N'Echuca-Moama', N'New South Wales', 0.04) 
	,('AU', N'Emerald', N'Queensland', 0.06) 
	,('AU', N'Esperance', N'Western Australia', 0.05) 
	,('AU', N'Forster-Tuncurry', N'New South Wales', 0.08) 
	,('AU', N'Geelong', N'Victoria', 1.07) 
	,('AU', N'Geraldton', N'Western Australia', 0.15) 
	,('AU', N'Gisborne-Macedon', N'Victoria', 0.09) 
	,('AU', N'Gladstone-Tannum Sands', N'Queensland', 0.18) 
	,('AU', N'Gold Coast-Tweed Heads', N'New South Wales', 1.36) 
	,('AU', N'Gold Coast-Tweed Heads', N'Queensland', 1.36) 
	,('AU', N'Goulburn', N'New South Wales', 0.1) 
	,('AU', N'Grafton', N'New South Wales', 0.08) 
	,('AU', N'Griffith', N'New South Wales', 0.08) 
	,('AU', N'Gympie', N'Queensland', 0.09) 
	,('AU', N'Hervey Bay', N'Queensland', 0.22) 
	,('AU', N'Hobart', N'Tasmania', 0.93) 
	,('AU', N'Horsham', N'Victoria', 0.07) 
	,('AU', N'Kalgoorlie-Boulder', N'Western Australia', 0.12) 
	,('AU', N'Karratha', N'Western Australia', 0.07) 
	,('AU', N'Kempsey', N'New South Wales', 0.06) 
	,('AU', N'Kingaroy', N'Queensland', 0.04) 
	,('AU', N'Launceston', N'Tasmania', 0.35) 
	,('AU', N'Lismore', N'New South Wales', 0.11) 
	,('AU', N'Lithgow', N'New South Wales', 0.05) 
	,('AU', N'Mackay', N'Queensland', 0.32) 
	,('AU', N'Maryborough', N'Queensland', 0.11) 
	,('AU', N'Melbourne', N'Victoria', 19.86) 
	,('AU', N'Melton', N'Victoria', 0.29) 
	,('AU', N'Mildura-Wentworth', N'Victoria', 0.11) 
	,('AU', N'Mildura-Wentworth', N'New South Wales', 0.1) 
	,('AU', N'Moe-Newborough', N'Victoria', 0.07) 
	,('AU', N'Morisset-Cooranbong', N'New South Wales', 0.1) 
	,('AU', N'Mount Gambier', N'South Australia', 0.12) 
	,('AU', N'Mount Isa', N'Queensland', 0.07) 
	,('AU', N'Mudgee', N'New South Wales', 0.05) 
	,('AU', N'Murray Bridge', N'South Australia', 0.08) 
	,('AU', N'Muswellbrook', N'New South Wales', 0.05) 
	,('AU', N'Nelson Bay', N'New South Wales', 0.11) 
	,('AU', N'Newcastle-Maitland', N'New South Wales', 1.95) 
	,('AU', N'Nowra-Bomaderry', N'New South Wales', 0.15) 
	,('AU', N'Orange', N'New South Wales', 0.16) 
	,('AU', N'Parkes', N'New South Wales', 0.04) 
	,('AU', N'Perth', N'Western Australia', 8.24) 
	,('AU', N'Port Augusta', N'South Australia', 0.06) 
	,('AU', N'Port Hedland', N'Western Australia', 0.06) 
	,('AU', N'Port Lincoln', N'South Australia', 0.07) 
	,('AU', N'Port Macquarie', N'New South Wales', 0.19) 
	,('AU', N'Port Pirie', N'South Australia', 0.06) 
	,('AU', N'Portland', N'Victoria', 0.04) 
	,('AU', N'Rockhampton', N'Queensland', 0.31) 
	,('AU', N'Sale', N'Victoria', 0.06) 
	,('AU', N'Shepparton-Mooroopna', N'Victoria', 0.21) 
	,('AU', N'Singleton', N'New South Wales', 0.07) 
	,('AU', N'St Georges Basin-Sanctuary Point', N'New South Wales', 0.08) 
	,('AU', N'Sunshine Coast', N'Queensland', 1.33) 
	,('AU', N'Swan Hill', N'Victoria', 0.04) 
	,('AU', N'Sydney', N'New South Wales', 20.93) 
	,('AU', N'Tamworth', N'New South Wales', 0.17) 
	,('AU', N'Taree', N'New South Wales', 0.11) 
	,('AU', N'Toowoomba', N'Queensland', 0.55) 
	,('AU', N'Townsville', N'Queensland', 0.72) 
	,('AU', N'Traralgon-Morwell', N'Victoria', 0.17) 
	,('AU', N'Ulladulla', N'New South Wales', 0.06) 
	,('AU', N'Ulverstone', N'Tasmania', 0.06) 
	,('AU', N'Victor Harbor-Goolwa', N'South Australia', 0.11) 
	,('AU', N'Wagga Wagga', N'New South Wales', 0.23) 
	,('AU', N'Wangaratta', N'Victoria', 0.08) 
	,('AU', N'Warragul-Drouin', N'Victoria', 0.15) 
	,('AU', N'Warrnambool', N'Victoria', 0.14) 
	,('AU', N'Warwick', N'Queensland', 0.06) 
	,('AU', N'Whyalla', N'South Australia', 0.09) 
	,('AU', N'Wollongong', N'New South Wales', 1.21) 
	,('AU', N'Yanchep', N'Western Australia', 0.06) 
	,('AU', N'Yeppoon', N'Queensland', 0.08) 
	,('BR', N'Abaetetuba', N'�Par�', 0.13) 
	,('BR', N'Abreu e Lima', N'�Pernambuco', 0.08) 
	,('BR', N'A�ail�ndia', N'�Maranh�o', 0.09) 
	,('BR', N'�guas Lindas de Goi�s', N'�Goi�s', 0.18) 
	,('BR', N'Alagoinhas', N'�Bahia', 0.12) 
	,('BR', N'Almirante Tamandar�', N'�Paran�', 0.1) 
	,('BR', N'Altamira', N'�Par�', 0.1) 
	,('BR', N'Alvorada', N'�Rio Grande do Sul', 0.17) 
	,('BR', N'Americana', N'�S�o Paulo', 0.2) 
	,('BR', N'Ananindeua', N'�Par�', 0.44) 
	,('BR', N'An�polis', N'�Goi�s', 0.32) 
	,('BR', N'Angra dos Reis', N'�Rio de Janeiro', 0.17) 
	,('BR', N'Aparecida de Goi�nia', N'�Goi�s', 0.49) 
	,('BR', N'Apucarana', N'�Paran�', 0.11) 
	,('BR', N'Aracaju', N'�Sergipe', 0.55) 
	,('BR', N'Ara�atuba', N'�S�o Paulo', 0.16) 
	,('BR', N'Aracruz', N'�Esp�rito Santo', 0.09) 
	,('BR', N'Aragua�na', N'�Tocantins', 0.15) 
	,('BR', N'Araguari', N'�Minas Gerais', 0.1) 
	,('BR', N'Arapiraca', N'�Alagoas', 0.19) 
	,('BR', N'Arapongas', N'�Paran�', 0.1) 
	,('BR', N'Araraquara', N'�S�o Paulo', 0.2) 
	,('BR', N'Araras', N'�S�o Paulo', 0.11) 
	,('BR', N'Araruama', N'�Rio de Janeiro', 0.11) 
	,('BR', N'Arauc�ria', N'�Paran�', 0.12) 
	,('BR', N'Arax�', N'�Minas Gerais', 0.09) 
	,('BR', N'Ariquemes', N'�Rond�nia', 0.09) 
	,('BR', N'Assis', N'�S�o Paulo', 0.09) 
	,('BR', N'Atibaia', N'�S�o Paulo', 0.12) 
	,('BR', N'Bacabal', N'�Maranh�o', 0.09) 
	,('BR', N'Bag�', N'�Rio Grande do Sul', 0.1) 
	,('BR', N'Balne�rio Cambori�', N'�Santa Catarina', 0.12) 
	,('BR', N'Barbacena', N'�Minas Gerais', 0.11) 
	,('BR', N'Barcarena', N'�Par�', 0.11) 
	,('BR', N'Barra do Pira�', N'�Rio de Janeiro', 0.08) 
	,('BR', N'Barra Mansa', N'�Rio de Janeiro', 0.15) 
	,('BR', N'Barreiras', N'�Bahia', 0.13) 
	,('BR', N'Barretos', N'�S�o Paulo', 0.1) 
	,('BR', N'Barueri', N'�S�o Paulo', 0.23) 
	,('BR', N'Bauru', N'�S�o Paulo', 0.31) 
	,('BR', N'Bel�m', N'�Par�', 1.22) 
	,('BR', N'Belford Roxo', N'�Rio de Janeiro', 0.42) 
	,('BR', N'Belo Horizonte', N'�Minas Gerais', 2.06) 
	,('BR', N'Bento Gon�alves', N'�Rio Grande do Sul', 0.1) 
	,('BR', N'Betim', N'�Minas Gerais', 0.37) 
	,('BR', N'Birigui', N'�S�o Paulo', 0.1) 
	,('BR', N'Blumenau', N'�Santa Catarina', 0.3) 
	,('BR', N'Boa Vista', N'�Roraima', 0.35) 
	,('BR', N'Botucatu', N'�S�o Paulo', 0.12) 
	,('BR', N'Bragan�a', N'�Par�', 0.11) 
	,('BR', N'Bragan�a Paulista', N'�S�o Paulo', 0.14) 
	,('BR', N'Bras�lia', N'�Distrito Federal', 2.52) 
	,('BR', N'Breves', N'�Par�', 0.08) 
	,('BR', N'Brusque', N'�Santa Catarina', 0.11) 
	,('BR', N'Cabo de Santo Agostinho', N'�Pernambuco', 0.17) 
	,('BR', N'Cabo Frio', N'�Rio de Janeiro', 0.19) 
	,('BR', N'Cachoeirinha', N'�Rio Grande do Sul', 0.11) 
	,('BR', N'Cachoeiro de Itapemirim', N'�Esp�rito Santo', 0.17) 
	,('BR', N'Caieiras', N'�S�o Paulo', 0.08) 
	,('BR', N'Cama�ari', N'�Bahia', 0.25) 
	,('BR', N'Camaragibe', N'�Pernambuco', 0.13) 
	,('BR', N'Camb�', N'�Paran�', 0.09) 
	,('BR', N'Camet�', N'�Par�', 0.11) 
	,('BR', N'Campina Grande', N'�Para�ba', 0.34) 
	,('BR', N'Campinas', N'�S�o Paulo', 0.99) 
	,('BR', N'Campo Grande', N'�Mato Grosso do Sul', 0.74) 
	,('BR', N'Campo Largo', N'�Paran�', 0.11) 
	,('BR', N'Campos dos Goytacazes', N'�Rio de Janeiro', 0.42) 
	,('BR', N'Canoas', N'�Rio Grande do Sul', 0.28) 
	,('BR', N'Caraguatatuba', N'�S�o Paulo', 0.1) 
	,('BR', N'Carapicu�ba', N'�S�o Paulo', 0.33) 
	,('BR', N'Cariacica', N'�Esp�rito Santo', 0.31) 
	,('BR', N'Caruaru', N'�Pernambuco', 0.3) 
	,('BR', N'Cascavel', N'�Paran�', 0.27) 
	,('BR', N'Castanhal', N'�Par�', 0.17) 
	,('BR', N'Catal�o', N'�Goi�s', 0.09) 
	,('BR', N'Catanduva', N'�S�o Paulo', 0.1) 
	,('BR', N'Caucaia', N'�Cear�', 0.3) 
	,('BR', N'Caxias', N'�Maranh�o', 0.14) 
	,('BR', N'Caxias do Sul', N'�Rio Grande do Sul', 0.43) 
	,('BR', N'Chapec�', N'�Santa Catarina', 0.18) 
	,('BR', N'Cod�', N'�Maranh�o', 0.1) 
	,('BR', N'Colatina', N'�Esp�rito Santo', 0.1) 
	,('BR', N'Colombo', N'�Paran�', 0.2) 
	,('BR', N'Conselheiro Lafaiete', N'�Minas Gerais', 0.11) 
	,('BR', N'Contagem', N'�Minas Gerais', 0.55) 
	,('BR', N'Coronel Fabriciano', N'�Minas Gerais', 0.09) 
	,('BR', N'Corumb�', N'�Mato Grosso do Sul', 0.09) 
	,('BR', N'Cotia', N'�S�o Paulo', 0.21) 
	,('BR', N'Crato', N'�Cear�', 0.11) 
	,('BR', N'Crici�ma', N'�Santa Catarina', 0.18) 
	,('BR', N'Cubat�o', N'�S�o Paulo', 0.11) 
	,('BR', N'Cuiab�', N'�Mato Grosso', 0.51) 
	,('BR', N'Curitiba', N'�Paran�', 1.6) 
	,('BR', N'Diadema', N'�S�o Paulo', 0.35) 
	,('BR', N'Divin�polis', N'�Minas Gerais', 0.2) 
	,('BR', N'Dourados', N'�Mato Grosso do Sul', 0.19) 
	,('BR', N'Duque de Caxias', N'�Rio de Janeiro', 0.76) 
	,('BR', N'Embu das Artes', N'�S�o Paulo', 0.23) 
	,('BR', N'Erechim', N'�Rio Grande do Sul', 0.09) 
	,('BR', N'Eun�polis', N'�Bahia', 0.09) 
	,('BR', N'Fazenda Rio Grande', N'�Paran�', 0.08) 
	,('BR', N'Feira de Santana', N'�Bahia', 0.51) 
	,('BR', N'Ferraz de Vasconcelos', N'�S�o Paulo', 0.16) 
	,('BR', N'Florian�polis', N'�Santa Catarina', 0.42) 
	,('BR', N'Formosa', N'�Goi�s', 0.1) 
	,('BR', N'Fortaleza', N'�Cear�', 2.2) 
	,('BR', N'Foz do Igua�u', N'�Paran�', 0.21) 
	,('BR', N'Franca', N'�S�o Paulo', 0.29) 
	,('BR', N'Francisco Morato', N'�S�o Paulo', 0.15) 
	,('BR', N'Franco da Rocha', N'�S�o Paulo', 0.13) 
	,('BR', N'Garanhuns', N'�Pernambuco', 0.11) 
	,('BR', N'Goi�nia', N'�Goi�s', 1.26) 
	,('BR', N'Governador Valadares', N'�Minas Gerais', 0.23) 
	,('BR', N'Gravata�', N'�Rio Grande do Sul', 0.23) 
	,('BR', N'Guarapari', N'�Esp�rito Santo', 0.1) 
	,('BR', N'Guarapuava', N'�Paran�', 0.15) 
	,('BR', N'Guaratinguet�', N'�S�o Paulo', 0.1) 
	,('BR', N'Guaruj�', N'�S�o Paulo', 0.26) 
	,('BR', N'Guarulhos', N'�S�o Paulo', 1.14) 
	,('BR', N'Hortol�ndia', N'�S�o Paulo', 0.19) 
	,('BR', N'Ibirit�', N'�Minas Gerais', 0.15) 
	,('BR', N'Igarassu', N'�Pernambuco', 0.1) 
	,('BR', N'Iguatu', N'�Cear�', 0.08) 
	,('BR', N'Ilh�us', N'�Bahia', 0.13) 
	,('BR', N'Imperatriz', N'�Maranh�o', 0.21) 
	,('BR', N'Indaiatuba', N'�S�o Paulo', 0.21) 
	,('BR', N'Ipatinga', N'�Minas Gerais', 0.22) 
	,('BR', N'Itabira', N'�Minas Gerais', 0.1) 
	,('BR', N'Itabora�', N'�Rio de Janeiro', 0.2) 
	,('BR', N'Itabuna', N'�Bahia', 0.17) 
	,('BR', N'Itacoatiara', N'�Amazonas', 0.08) 
	,('BR', N'Itagua�', N'�Rio de Janeiro', 0.11) 
	,('BR', N'Itaituba', N'�Par�', 0.08) 
	,('BR', N'Itaja�', N'�Santa Catarina', 0.18) 
	,('BR', N'Itanha�m', N'�S�o Paulo', 0.08) 
	,('BR', N'Itapecerica da Serra', N'�S�o Paulo', 0.15) 
	,('BR', N'Itaperuna', N'�Rio de Janeiro', 0.08) 
	,('BR', N'Itapetininga', N'�S�o Paulo', 0.14) 
	,('BR', N'Itapevi', N'�S�o Paulo', 0.2) 
	,('BR', N'Itapipoca', N'�Cear�', 0.11) 
	,('BR', N'Itaquaquecetuba', N'�S�o Paulo', 0.31) 
	,('BR', N'Itatiba', N'�S�o Paulo', 0.1) 
	,('BR', N'Itu', N'�S�o Paulo', 0.14) 
	,('BR', N'Ituiutaba', N'�Minas Gerais', 0.09) 
	,('BR', N'Itumbiara', N'�Goi�s', 0.09) 
	,('BR', N'Jaboat�o dos Guararapes', N'�Pernambuco', 0.58) 
	,('BR', N'Jacare�', N'�S�o Paulo', 0.19) 
	,('BR', N'Jandira', N'�S�o Paulo', 0.1) 
	,('BR', N'Japeri', N'�Rio de Janeiro', 0.09) 
	,('BR', N'Jaragu� do Sul', N'�Santa Catarina', 0.15) 
	,('BR', N'Jata�', N'�Goi�s', 0.08) 
	,('BR', N'Ja�', N'�S�o Paulo', 0.12) 
	,('BR', N'Jequi�', N'�Bahia', 0.13) 
	,('BR', N'Ji-Paran�', N'�Rond�nia', 0.11) 
	,('BR', N'Jo�o Pessoa', N'�Para�ba', 0.67) 
	,('BR', N'Joinville', N'�Santa Catarina', 0.49) 
	,('BR', N'Juazeiro', N'�Bahia', 0.18) 
	,('BR', N'Juazeiro do Norte', N'�Cear�', 0.23) 
	,('BR', N'Juiz de Fora', N'�Minas Gerais', 0.47) 
	,('BR', N'Jundia�', N'�S�o Paulo', 0.35) 
	,('BR', N'Lagarto', N'�Sergipe', 0.09) 
	,('BR', N'Lages', N'�Santa Catarina', 0.13) 
	,('BR', N'Lauro de Freitas', N'�Bahia', 0.17) 
	,('BR', N'Lavras', N'�Minas Gerais', 0.09) 
	,('BR', N'Leme', N'�S�o Paulo', 0.09) 
	,('BR', N'Limeira', N'�S�o Paulo', 0.25) 
	,('BR', N'Linhares', N'�Esp�rito Santo', 0.15) 
	,('BR', N'Londrina', N'�Paran�', 0.47) 
	,('BR', N'Luzi�nia', N'�Goi�s', 0.17) 
	,('BR', N'Maca�', N'�Rio de Janeiro', 0.22) 
	,('BR', N'Macap�', N'�Amap�', 0.42) 
	,('BR', N'Macei�', N'�Alagoas', 0.84) 
	,('BR', N'Mag�', N'�Rio de Janeiro', 0.2) 
	,('BR', N'Mairipor�', N'�S�o Paulo', 0.08) 
	,('BR', N'Manaus', N'�Amazonas', 1.83) 
	,('BR', N'Marab�', N'�Par�', 0.23) 
	,('BR', N'Maracana�', N'�Cear�', 0.19) 
	,('BR', N'Maranguape', N'�Cear�', 0.11) 
	,('BR', N'Maric�', N'�Rio de Janeiro', 0.14) 
	,('BR', N'Mar�lia', N'�S�o Paulo', 0.2) 
	,('BR', N'Maring�', N'�Paran�', 0.35) 
	,('BR', N'Marituba', N'�Par�', 0.11) 
	,('BR', N'Mau�', N'�S�o Paulo', 0.39) 
	,('BR', N'Mesquita', N'�Rio de Janeiro', 0.14) 
	,('BR', N'Mogi das Cruzes', N'�S�o Paulo', 0.37) 
	,('BR', N'Mogi Gua�u', N'�S�o Paulo', 0.13) 
	,('BR', N'Montes Claros', N'�Minas Gerais', 0.34) 
	,('BR', N'Mossor�', N'�Rio Grande do Norte', 0.25) 
	,('BR', N'Muria�', N'�Minas Gerais', 0.09) 
	,('BR', N'Natal', N'�Rio Grande do Norte', 0.73) 
	,('BR', N'Nil�polis', N'�Rio de Janeiro', 0.13) 
	,('BR', N'Niter�i', N'�Rio de Janeiro', 0.42) 
	,('BR', N'Nossa Senhora do Socorro', N'�Sergipe', 0.15) 
	,('BR', N'Nova Friburgo', N'�Rio de Janeiro', 0.16) 
	,('BR', N'Nova Igua�u', N'�Rio de Janeiro', 0.67) 
	,('BR', N'Nova Serrana', N'�Minas Gerais', 0.09) 
	,('BR', N'Novo Gama', N'�Goi�s', 0.1) 
	,('BR', N'Novo Hamburgo', N'�Rio Grande do Sul', 0.2) 
	,('BR', N'Olinda', N'�Pernambuco', 0.32) 
	,('BR', N'Osasco', N'�S�o Paulo', 0.57) 
	,('BR', N'Ourinhos', N'�S�o Paulo', 0.09) 
	,('BR', N'Pa�o do Lumiar', N'�Maranh�o', 0.1) 
	,('BR', N'Palho�a', N'�Santa Catarina', 0.15) 
	,('BR', N'Palmas', N'�Tocantins', 0.25) 
	,('BR', N'Paragominas', N'�Par�', 0.09) 
	,('BR', N'Paranagu�', N'�Paran�', 0.13) 
	,('BR', N'Parauapebas', N'�Par�', 0.18) 
	,('BR', N'Parintins', N'�Amazonas', 0.09) 
	,('BR', N'Parna�ba', N'�Piau�', 0.13) 
	,('BR', N'Parnamirim', N'�Rio Grande do Norte', 0.22) 
	,('BR', N'Passo Fundo', N'�Rio Grande do Sul', 0.17) 
	,('BR', N'Passos', N'�Minas Gerais', 0.09) 
	,('BR', N'Patos', N'�Para�ba', 0.09) 
	,('BR', N'Patos de Minas', N'�Minas Gerais', 0.13) 
	,('BR', N'Paul�nia', N'�S�o Paulo', 0.09) 
	,('BR', N'Paulista', N'�Pernambuco', 0.27) 
	,('BR', N'Paulo Afonso', N'�Bahia', 0.1) 
	,('BR', N'Pelotas', N'�Rio Grande do Sul', 0.28) 
	,('BR', N'Petrolina', N'�Pernambuco', 0.29) 
	,('BR', N'Petr�polis', N'�Rio de Janeiro', 0.25) 
	,('BR', N'Pindamonhangaba', N'�S�o Paulo', 0.14) 
	,('BR', N'Pinhais', N'�Paran�', 0.11) 
	,('BR', N'Piracicaba', N'�S�o Paulo', 0.33) 
	,('BR', N'Piraquara', N'�Paran�', 0.09) 
	,('BR', N'Po�', N'�S�o Paulo', 0.1) 
	,('BR', N'Po�os de Caldas', N'�Minas Gerais', 0.14) 
	,('BR', N'Ponta Grossa', N'�Paran�', 0.29) 
	,('BR', N'Porto Alegre', N'�Rio Grande do Sul', 1.21) 
	,('BR', N'Porto Seguro', N'�Bahia', 0.12) 
	,('BR', N'Porto Velho', N'�Rond�nia', 0.45) 
	,('BR', N'Pouso Alegre', N'�Minas Gerais', 0.13) 
	,('BR', N'Praia Grande', N'�S�o Paulo', 0.27) 
	,('BR', N'Presidente Prudente', N'�S�o Paulo', 0.19) 
	,('BR', N'Queimados', N'�Rio de Janeiro', 0.12) 
	,('BR', N'Recife', N'�Pernambuco', 1.35) 
	,('BR', N'Resende', N'�Rio de Janeiro', 0.11) 
	,('BR', N'Ribeir�o das Neves', N'�Minas Gerais', 0.28) 
	,('BR', N'Ribeir�o Pires', N'�S�o Paulo', 0.1) 
	,('BR', N'Ribeir�o Preto', N'�S�o Paulo', 0.59) 
	,('BR', N'Rio Branco', N'�Acre', 0.34) 
	,('BR', N'Rio Claro', N'�S�o Paulo', 0.17) 
	,('BR', N'Rio das Ostras', N'�Rio de Janeiro', 0.13) 
	,('BR', N'Rio de Janeiro', N'�Rio de Janeiro', 5.51) 
	,('BR', N'Rio Grande', N'�Rio Grande do Sul', 0.17) 
	,('BR', N'Rio Verde', N'�Goi�s', 0.2) 
	,('BR', N'Rondon�polis', N'�Mato Grosso', 0.19) 
	,('BR', N'Sabar�', N'�Minas Gerais', 0.11) 
	,('BR', N'Salto', N'�S�o Paulo', 0.1) 
	,('BR', N'Salvador', N'�Bahia', 2.36) 
	,('BR', N'Santa B�rbara d''Oeste', N'�S�o Paulo', 0.16) 
	,('BR', N'Santa Cruz do Capibaribe', N'�Pernambuco', 0.09) 
	,('BR', N'Santa Cruz do Sul', N'�Rio Grande do Sul', 0.11) 
	,('BR', N'Santa Luzia', N'�Minas Gerais', 0.18) 
	,('BR', N'Santa Maria', N'�Rio Grande do Sul', 0.23) 
	,('BR', N'Santa Rita', N'�Para�ba', 0.11) 
	,('BR', N'Santana', N'�Amap�', 0.1) 
	,('BR', N'Santana de Parna�ba', N'�S�o Paulo', 0.12) 
	,('BR', N'Santar�m', N'�Par�', 0.25) 
	,('BR', N'Santo Andr�', N'�S�o Paulo', 0.59) 
	,('BR', N'Santo Ant�nio de Jesus', N'�Bahia', 0.08) 
	,('BR', N'Santos', N'�S�o Paulo', 0.35) 
	,('BR', N'S�o Bernardo do Campo', N'�S�o Paulo', 0.69) 
	,('BR', N'S�o Caetano do Sul', N'�S�o Paulo', 0.13) 
	,('BR', N'S�o Carlos', N'�S�o Paulo', 0.21) 
	,('BR', N'S�o F�lix do Xingu', N'�Par�', 0.11) 
	,('BR', N'S�o Gon�alo', N'�Rio de Janeiro', 0.89) 
	,('BR', N'S�o Gon�alo do Amarante', N'�Rio Grande do Norte', 0.09) 
	,('BR', N'S�o Jo�o de Meriti', N'�Rio de Janeiro', 0.38) 
	,('BR', N'S�o Jos�', N'�Santa Catarina', 0.21) 
	,('BR', N'S�o Jos� de Ribamar', N'�Maranh�o', 0.15) 
	,('BR', N'S�o Jos� do Rio Preto', N'�S�o Paulo', 0.38) 
	,('BR', N'S�o Jos� dos Campos', N'�S�o Paulo', 0.6) 
	,('BR', N'S�o Jos� dos Pinhais', N'�Paran�', 0.27) 
	,('BR', N'S�o Leopoldo', N'�Rio Grande do Sul', 0.2) 
	,('BR', N'S�o Louren�o da Mata', N'�Pernambuco', 0.09) 
	,('BR', N'S�o Lu�s', N'�Maranh�o', 0.91) 
	,('BR', N'S�o Mateus', N'�Esp�rito Santo', 0.11) 
	,('BR', N'S�o Paulo', N'�S�o Paulo', 10.08) 
	,('BR', N'S�o Pedro da Aldeia', N'�Rio de Janeiro', 0.09) 
	,('BR', N'S�o Vicente', N'�S�o Paulo', 0.3) 
	,('BR', N'Sapucaia do Sul', N'�Rio Grande do Sul', 0.12) 
	,('BR', N'Senador Canedo', N'�Goi�s', 0.1) 
	,('BR', N'Serra', N'�Esp�rito Santo', 0.44) 
	,('BR', N'Sert�ozinho', N'�S�o Paulo', 0.1) 
	,('BR', N'Sete Lagoas', N'�Minas Gerais', 0.2) 
	,('BR', N'Sim�es Filho', N'�Bahia', 0.11) 
	,('BR', N'Sinop', N'�Mato Grosso', 0.12) 
	,('BR', N'Sobral', N'�Cear�', 0.17) 
	,('BR', N'Sorocaba', N'�S�o Paulo', 0.57) 
	,('BR', N'Sumar�', N'�S�o Paulo', 0.24) 
	,('BR', N'Suzano', N'�S�o Paulo', 0.25) 
	,('BR', N'Tabo�o da Serra', N'�S�o Paulo', 0.24) 
	,('BR', N'Tail�ndia', N'�Par�', 0.09) 
	,('BR', N'Tangar� da Serra', N'�Mato Grosso', 0.09) 
	,('BR', N'Tatu�', N'�S�o Paulo', 0.1) 
	,('BR', N'Taubat�', N'�S�o Paulo', 0.26) 
	,('BR', N'Teixeira de Freitas', N'�Bahia', 0.13) 
	,('BR', N'Te�filo Otoni', N'�Minas Gerais', 0.11) 
	,('BR', N'Teresina', N'�Piau�', 0.71) 
	,('BR', N'Teres�polis', N'�Rio de Janeiro', 0.15) 
	,('BR', N'Timon', N'�Maranh�o', 0.14) 
	,('BR', N'Toledo', N'�Paran�', 0.12) 
	,('BR', N'Tr�s Lagoas', N'�Mato Grosso do Sul', 0.1) 
	,('BR', N'Trindade', N'�Goi�s', 0.11) 
	,('BR', N'Tubar�o', N'�Santa Catarina', 0.09) 
	,('BR', N'Tucuru�', N'�Par�', 0.09) 
	,('BR', N'Ub�', N'�Minas Gerais', 0.1) 
	,('BR', N'Uberaba', N'�Minas Gerais', 0.28) 
	,('BR', N'Uberl�ndia', N'�Minas Gerais', 0.57) 
	,('BR', N'Umuarama', N'�Paran�', 0.09) 
	,('BR', N'Uruguaiana', N'�Rio Grande do Sul', 0.1) 
	,('BR', N'Valinhos', N'�S�o Paulo', 0.11) 
	,('BR', N'Valpara�so de Goi�s', N'�Goi�s', 0.14) 
	,('BR', N'Varginha', N'�Minas Gerais', 0.11) 
	,('BR', N'V�rzea Grande', N'�Mato Grosso', 0.24) 
	,('BR', N'V�rzea Paulista', N'�S�o Paulo', 0.1) 
	,('BR', N'Vespasiano', N'�Minas Gerais', 0.11) 
	,('BR', N'Viam�o', N'�Rio Grande do Sul', 0.21) 
	,('BR', N'Vila Velha', N'�Esp�rito Santo', 0.41) 
	,('BR', N'Vilhena', N'�Rond�nia', 0.08) 
	,('BR', N'Vit�ria', N'�Esp�rito Santo', 0.3) 
	,('BR', N'Vit�ria da Conquista', N'�Bahia', 0.28) 
	,('BR', N'Vit�ria de Santo Ant�o', N'�Pernambuco', 0.11) 
	,('BR', N'Volta Redonda', N'�Rio de Janeiro', 0.22) 
	,('BR', N'Votorantim', N'�S�o Paulo', 0.1) 
	,('CA', N'Abbotsford', N'British Columbia', 0.51) 
	,('CA', N'Airdrie', N'Alberta', 0.28) 
	,('CA', N'Barrie', N'Ontario', 0.59) 
	,('CA', N'Belleville', N'Ontario', 0.29) 
	,('CA', N'Beloeil', N'Quebec', 0.2) 
	,('CA', N'Bolton', N'Ontario', 0.1) 
	,('CA', N'Bowmanville�-�Newcastle', N'Ontario', 0.22) 
	,('CA', N'Bradford', N'Ontario', 0.15) 
	,('CA', N'Brandon', N'Manitoba', 0.19) 
	,('CA', N'Brantford', N'Ontario', 0.4) 
	,('CA', N'Calgary', N'Alberta', 5.02) 
	,('CA', N'Campbell River', N'British Columbia', 0.15) 
	,('CA', N'Cape Breton�-�Sydney', N'Nova Scotia', 0.12) 
	,('CA', N'Charlottetown', N'Prince Edward Island', 0.2) 
	,('CA', N'Ch�teauguay', N'Quebec', 0.29) 
	,('CA', N'Chatham', N'Ontario', 0.17) 
	,('CA', N'Chicoutimi�-�Jonqui�re', N'Quebec', 0.4) 
	,('CA', N'Chilliwack', N'British Columbia', 0.31) 
	,('CA', N'Cochrane', N'Alberta', 0.12) 
	,('CA', N'Cornwall', N'Ontario', 0.18) 
	,('CA', N'Courtenay', N'British Columbia', 0.19) 
	,('CA', N'Drummondville', N'Quebec', 0.28) 
	,('CA', N'Edmonton', N'Alberta', 4.42) 
	,('CA', N'Fort McMurray', N'Alberta', 0.26) 
	,('CA', N'Fort Saskatchewan', N'Alberta', 0.1) 
	,('CA', N'Fredericton', N'New Brunswick', 0.25) 
	,('CA', N'Georgetown', N'Ontario', 0.17) 
	,('CA', N'Granby', N'Quebec', 0.24) 
	,('CA', N'Grande Prairie', N'Alberta', 0.24) 
	,('CA', N'Guelph', N'Ontario', 0.55) 
	,('CA', N'Halifax', N'Nova Scotia', 1.34) 
	,('CA', N'Hamilton', N'Ontario', 2.8) 
	,('CA', N'Innisfil', N'Ontario', 0.11) 
	,('CA', N'Joliette', N'Quebec', 0.19) 
	,('CA', N'Kamloops', N'British Columbia', 0.36) 
	,('CA', N'Kanata', N'Ontario', 0.53) 
	,('CA', N'Kelowna', N'British Columbia', 0.7) 
	,('CA', N'Keswick�-�Elmhurst Beach', N'Ontario', 0.1) 
	,('CA', N'Kingston', N'Ontario', 0.49) 
	,('CA', N'Kitchener', N'Ontario', 2.01) 
	,('CA', N'Leamington', N'Ontario', 0.14) 
	,('CA', N'Leduc', N'Alberta', 0.13) 
	,('CA', N'Lethbridge', N'Alberta', 0.36) 
	,('CA', N'Lloydminster', N'Alberta�/�Saskatchewan', 0.12) 
	,('CA', N'London', N'Ontario', 1.63) 
	,('CA', N'Medicine Hat', N'Alberta', 0.24) 
	,('CA', N'Midland', N'Ontario', 0.1) 
	,('CA', N'Milton', N'Ontario', 0.48) 
	,('CA', N'Mission', N'British Columbia', 0.14) 
	,('CA', N'Moncton', N'New Brunswick', 0.46) 
	,('CA', N'Montr�al', N'Quebec', 14.12) 
	,('CA', N'Moose Jaw', N'Saskatchewan', 0.13) 
	,('CA', N'Nanaimo', N'British Columbia', 0.41) 
	,('CA', N'North Bay', N'Ontario', 0.2) 
	,('CA', N'Okotoks', N'Alberta', 0.12) 
	,('CA', N'Orangeville', N'Ontario', 0.13) 
	,('CA', N'Orillia', N'Ontario', 0.13) 
	,('CA', N'Oshawa', N'Ontario', 1.29) 
	,('CA', N'Ottawa�-�Gatineau', N'Ontario�/�Quebec', 4.11) 
	,('CA', N'Parksville', N'British Columbia', 0.1) 
	,('CA', N'Penticton', N'British Columbia', 0.14) 
	,('CA', N'Peterborough', N'Ontario', 0.33) 
	,('CA', N'Prince Albert', N'Saskatchewan', 0.14) 
	,('CA', N'Prince George', N'British Columbia', 0.26) 
	,('CA', N'Qu�bec', N'Quebec', 2.82) 
	,('CA', N'Red Deer', N'Alberta', 0.38) 
	,('CA', N'Regina', N'Saskatchewan', 0.86) 
	,('CA', N'Rimouski', N'Quebec', 0.15) 
	,('CA', N'Saint John', N'New Brunswick', 0.24) 
	,('CA', N'Saint-Georges', N'Quebec', 0.11) 
	,('CA', N'Saint-Hyacinthe', N'Quebec', 0.19) 
	,('CA', N'Saint-Jean-sur-Richelieu', N'Quebec', 0.34) 
	,('CA', N'Saint-J�r�me', N'Quebec', 0.39) 
	,('CA', N'Salaberry-de-Valleyfield', N'Quebec', 0.16) 
	,('CA', N'Sarnia', N'Ontario', 0.28) 
	,('CA', N'Saskatoon', N'Saskatchewan', 1.02) 
	,('CA', N'Sault Ste. Marie', N'Ontario', 0.25) 
	,('CA', N'Shawinigan', N'Quebec', 0.15) 
	,('CA', N'Sherbrooke', N'Quebec', 0.58) 
	,('CA', N'Sorel', N'Quebec', 0.14) 
	,('CA', N'Spruce Grove', N'Alberta', 0.15) 
	,('CA', N'St. Catharines�-�Niagara Falls', N'Ontario', 0.93) 
	,('CA', N'St. John''s', N'Newfoundland and Labrador', 0.71) 
	,('CA', N'St. Thomas', N'Ontario', 0.18) 
	,('CA', N'Stouffville', N'Ontario', 0.14) 
	,('CA', N'Stratford', N'Ontario', 0.13) 
	,('CA', N'Sudbury', N'Ontario', 0.35) 
	,('CA', N'Thunder Bay', N'Ontario', 0.37) 
	,('CA', N'Timmins', N'Ontario', 0.11) 
	,('CA', N'Toronto', N'Ontario', 21.7) 
	,('CA', N'Trois-Rivi�res', N'Quebec', 0.49) 
	,('CA', N'Vancouver', N'British Columbia', 9.32) 
	,('CA', N'Vernon', N'British Columbia', 0.2) 
	,('CA', N'Victoria', N'British Columbia', 1.4) 
	,('CA', N'Victoriaville', N'Quebec', 0.18) 
	,('CA', N'Welland�-�Pelham', N'Ontario', 0.27) 
	,('CA', N'White Rock', N'British Columbia', 0.42) 
	,('CA', N'Windsor', N'Ontario', 1.18) 
	,('CA', N'Winnipeg', N'Manitoba', 2.91) 
	,('CA', N'Woodstock', N'Ontario', 0.18) 
	,('DE', N'Aachen', N'North Rhine-Westphalia', 0.94) 
	,('DE', N'Augsburg', N'Bavaria', 1.1) 
	,('DE', N'Bergisch Gladbach', N'North Rhine-Westphalia', 0.43) 
	,('DE', N'Berlin', N'Berlin', 13.51) 
	,('DE', N'Bielefeld', N'North Rhine-Westphalia', 1.28) 
	,('DE', N'Bochum', N'North Rhine-Westphalia', 1.4) 
	,('DE', N'Bonn', N'North Rhine-Westphalia', 1.22) 
	,('DE', N'Bottrop', N'North Rhine-Westphalia', 0.45) 
	,('DE', N'Braunschweig', N'Lower Saxony', 0.96) 
	,('DE', N'Bremen', N'Bremen', 2.14) 
	,('DE', N'Bremerhaven', N'Bremen', 0.44) 
	,('DE', N'Chemnitz', N'Saxony', 0.95) 
	,('DE', N'Cologne', N'North Rhine-Westphalia', 4.07) 
	,('DE', N'Darmstadt', N'Hesse', 0.6) 
	,('DE', N'Dortmund', N'North Rhine-Westphalia', 2.25) 
	,('DE', N'Dresden', N'Saxony', 2.09) 
	,('DE', N'Duisburg', N'North Rhine-Westphalia', 1.89) 
	,('DE', N'Düsseldorf', N'North Rhine-Westphalia', 2.35) 
	,('DE', N'Erfurt', N'Thuringia', 0.81) 
	,('DE', N'Erlangen', N'Bavaria', 0.42) 
	,('DE', N'Essen', N'North Rhine-Westphalia', 2.24) 
	,('DE', N'Frankfurt am Main', N'Hesse', 2.81) 
	,('DE', N'Freiburg im Breisgau', N'Baden-Württemberg', 0.87) 
	,('DE', N'Fürth', N'Bavaria', 0.48) 
	,('DE', N'Gelsenkirchen', N'North Rhine-Westphalia', 1.0) 
	,('DE', N'Göttingen', N'Lower Saxony', 0.46) 
	,('DE', N'Hagen', N'North Rhine-Westphalia', 0.73) 
	,('DE', N'Halle', N'Saxony-Anhalt', 0.91) 
	,('DE', N'Hamburg', N'Hamburg', 6.86) 
	,('DE', N'Hamm', N'North Rhine-Westphalia', 0.69) 
	,('DE', N'Hanover', N'Lower Saxony', 2.04) 
	,('DE', N'Heidelberg', N'Baden-Württemberg', 0.6) 
	,('DE', N'Heilbronn', N'Baden-Württemberg', 0.47) 
	,('DE', N'Herne', N'North Rhine-Westphalia', 0.6) 
	,('DE', N'Hildesheim', N'Lower Saxony', 0.39) 
	,('DE', N'Ingolstadt', N'Bavaria', 0.51) 
	,('DE', N'Jena', N'Thuringia', 0.42) 
	,('DE', N'Kaiserslautern', N'Rhineland-Palatinate', 0.38) 
	,('DE', N'Karlsruhe', N'Baden-Württemberg', 1.18) 
	,('DE', N'Kassel', N'Hesse', 0.76) 
	,('DE', N'Kiel', N'Schleswig-Holstein', 0.95) 
	,('DE', N'Koblenz', N'Rhineland-Palatinate', 0.43) 
	,('DE', N'Krefeld', N'North Rhine-Westphalia', 0.86) 
	,('DE', N'Leipzig', N'Saxony', 2.15) 
	,('DE', N'Leverkusen', N'North Rhine-Westphalia', 0.63) 
	,('DE', N'Lübeck', N'Schleswig-Holstein', 0.83) 
	,('DE', N'Ludwigshafen am Rhein', N'Rhineland-Palatinate', 0.63) 
	,('DE', N'Magdeburg', N'Saxony-Anhalt', 0.9) 
	,('DE', N'Mainz', N'Rhineland-Palatinate', 0.81) 
	,('DE', N'Mannheim', N'Baden-Württemberg', 1.17) 
	,('DE', N'Moers', N'North Rhine-Westphalia', 0.4) 
	,('DE', N'Mönchengladbach', N'North Rhine-Westphalia', 1.0) 
	,('DE', N'Mülheim an der Ruhr', N'North Rhine-Westphalia', 0.65) 
	,('DE', N'Munich', N'Bavaria', 5.57) 
	,('DE', N'Münster', N'North Rhine-Westphalia', 1.19) 
	,('DE', N'Neuss', N'North Rhine-Westphalia', 0.6) 
	,('DE', N'Nuremberg', N'Bavaria', 1.96) 
	,('DE', N'Oberhausen', N'North Rhine-Westphalia', 0.81) 
	,('DE', N'Offenbach am Main', N'Hesse', 0.47) 
	,('DE', N'Oldenburg', N'Lower Saxony', 0.63) 
	,('DE', N'Osnabrück', N'Lower Saxony', 0.62) 
	,('DE', N'Paderborn', N'North Rhine-Westphalia', 0.57) 
	,('DE', N'Pforzheim', N'Baden-Württemberg', 0.47) 
	,('DE', N'Potsdam', N'Brandenburg', 0.64) 
	,('DE', N'Recklinghausen', N'North Rhine-Westphalia', 0.44) 
	,('DE', N'Regensburg', N'Bavaria', 0.56) 
	,('DE', N'Remscheid', N'North Rhine-Westphalia', 0.42) 
	,('DE', N'Reutlingen', N'Baden-Württemberg', 0.44) 
	,('DE', N'Rostock', N'Mecklenburg-Vorpommern', 0.79) 
	,('DE', N'Saarbrücken', N'Saarland', 0.68) 
	,('DE', N'Salzgitter', N'Lower Saxony', 0.39) 
	,('DE', N'Siegen', N'North Rhine-Westphalia', 0.39) 
	,('DE', N'Solingen', N'North Rhine-Westphalia', 0.61) 
	,('DE', N'Stuttgart', N'Baden-Württemberg', 2.39) 
	,('DE', N'Trier', N'Rhineland-Palatinate', 0.44) 
	,('DE', N'Ulm', N'Baden-Württemberg', 0.47) 
	,('DE', N'Wiesbaden', N'Hesse', 1.06) 
	,('DE', N'Wolfsburg', N'Lower Saxony', 0.48) 
	,('DE', N'Wuppertal', N'North Rhine-Westphalia', 1.34) 
	,('DE', N'Würzburg', N'Bavaria', 0.48) 
	,('FR', N'Abbeville', N'Hauts-de-France', 0.1) 
	,('FR', N'Agde', N'Occitanie', 0.1) 
	,('FR', N'Agen', N'Nouvelle-Aquitaine', 0.14) 
	,('FR', N'Aix-en-Provence', N'Provence-Alpes-Côte d''Azur', 0.57) 
	,('FR', N'Aix-les-Bains', N'Auvergne-Rhône-Alpes', 0.12) 
	,('FR', N'Ajaccio', N'Corsica', 0.27) 
	,('FR', N'Albi', N'Occitanie', 0.2) 
	,('FR', N'Alençon', N'Normandy', 0.11) 
	,('FR', N'Alès', N'Occitanie', 0.16) 
	,('FR', N'Alfortville', N'Île-de-France', 0.18) 
	,('FR', N'Amiens', N'Hauts-de-France', 0.53) 
	,('FR', N'Angers', N'Pays de la Loire', 0.6) 
	,('FR', N'Anglet', N'Nouvelle-Aquitaine', 0.16) 
	,('FR', N'Angoulême', N'Nouvelle-Aquitaine', 0.17) 
	,('FR', N'Annecy', N'Auvergne-Rhône-Alpes', 0.21) 
	,('FR', N'Annemasse', N'Auvergne-Rhône-Alpes', 0.14) 
	,('FR', N'Antibes', N'Provence-Alpes-Côte d''Azur', 0.3) 
	,('FR', N'Antony', N'Île-de-France', 0.25) 
	,('FR', N'Argenteuil', N'Île-de-France', 0.43) 
	,('FR', N'Arles', N'Provence-Alpes-Côte d''Azur', 0.21) 
	,('FR', N'Armentières', N'Hauts-de-France', 0.1) 
	,('FR', N'Arras', N'Hauts-de-France', 0.16) 
	,('FR', N'Asnières-sur-Seine', N'Île-de-France', 0.34) 
	,('FR', N'Athis-Mons', N'Île-de-France', 0.12) 
	,('FR', N'Aubagne', N'Provence-Alpes-Côte d''Azur', 0.18) 
	,('FR', N'Aubervilliers', N'Île-de-France', 0.31) 
	,('FR', N'Auch', N'Occitanie', 0.09) 
	,('FR', N'Aulnay-sous-Bois', N'Île-de-France', 0.33) 
	,('FR', N'Aurillac', N'Auvergne-Rhône-Alpes', 0.11) 
	,('FR', N'Auxerre', N'Bourgogne-Franche-Comté', 0.14) 
	,('FR', N'Avignon', N'Provence-Alpes-Côte d''Azur', 0.36) 
	,('FR', N'Bagneux', N'Île-de-France', 0.15) 
	,('FR', N'Bagnolet', N'Île-de-France', 0.14) 
	,('FR', N'Baie-Mahault', N'Guadeloupe', 0.12) 
	,('FR', N'Bastia', N'Corsica', 0.17) 
	,('FR', N'Bayonne', N'Nouvelle-Aquitaine', 0.19) 
	,('FR', N'Beaune', N'Bourgogne-Franche-Comté', 0.09) 
	,('FR', N'Beauvais', N'Hauts-de-France', 0.22) 
	,('FR', N'Bègles', N'Nouvelle-Aquitaine', 0.1) 
	,('FR', N'Belfort', N'Bourgogne-Franche-Comté', 0.2) 
	,('FR', N'Bergerac', N'Nouvelle-Aquitaine', 0.11) 
	,('FR', N'Besançon', N'Bourgogne-Franche-Comté', 0.47) 
	,('FR', N'Béthune', N'Hauts-de-France', 0.1) 
	,('FR', N'Béziers', N'Occitanie', 0.3) 
	,('FR', N'Bezons', N'Île-de-France', 0.11) 
	,('FR', N'Biarritz', N'Nouvelle-Aquitaine', 0.1) 
	,('FR', N'Blagnac', N'Occitanie', 0.09) 
	,('FR', N'Blois', N'Centre-Val de Loire', 0.18) 
	,('FR', N'Bobigny', N'Île-de-France', 0.2) 
	,('FR', N'Bois-Colombes', N'Île-de-France', 0.11) 
	,('FR', N'Bondy', N'Île-de-France', 0.21) 
	,('FR', N'Bordeaux', N'Nouvelle-Aquitaine', 0.98) 
	,('FR', N'Boulogne-Billancourt', N'Île-de-France', 0.47) 
	,('FR', N'Boulogne-sur-Mer', N'Hauts-de-France', 0.17) 
	,('FR', N'Bourg-en-Bresse', N'Auvergne-Rhône-Alpes', 0.16) 
	,('FR', N'Bourges', N'Centre-Val de Loire', 0.27) 
	,('FR', N'Bourgoin-Jallieu', N'Auvergne-Rhône-Alpes', 0.11) 
	,('FR', N'Brest', N'Brittany', 0.56) 
	,('FR', N'Brétigny-sur-Orge', N'Île-de-France', 0.1) 
	,('FR', N'Brive-la-Gaillarde', N'Nouvelle-Aquitaine', 0.19) 
	,('FR', N'Bron', N'Auvergne-Rhône-Alpes', 0.16) 
	,('FR', N'Bruay-la-Buissière', N'Hauts-de-France', 0.09) 
	,('FR', N'Brunoy', N'Île-de-France', 0.1) 
	,('FR', N'Bussy-Saint-Georges', N'Île-de-France', 0.1) 
	,('FR', N'Cachan', N'Île-de-France', 0.12) 
	,('FR', N'Caen', N'Normandy', 0.43) 
	,('FR', N'Cagnes-sur-Mer', N'Provence-Alpes-Côte d''Azur', 0.19) 
	,('FR', N'Calais', N'Hauts-de-France', 0.29) 
	,('FR', N'Caluire-et-Cuire', N'Auvergne-Rhône-Alpes', 0.17) 
	,('FR', N'Cambrai', N'Hauts-de-France', 0.13) 
	,('FR', N'Cannes', N'Provence-Alpes-Côte d''Azur', 0.29) 
	,('FR', N'Carcassonne', N'Occitanie', 0.19) 
	,('FR', N'Carpentras', N'Provence-Alpes-Côte d''Azur', 0.11) 
	,('FR', N'Castres', N'Occitanie', 0.17) 
	,('FR', N'Cavaillon', N'Provence-Alpes-Côte d''Azur', 0.1) 
	,('FR', N'Cayenne', N'French Guiana', 0.22) 
	,('FR', N'Cenon', N'Nouvelle-Aquitaine', 0.09) 
	,('FR', N'Cergy', N'Île-de-France', 0.25) 
	,('FR', N'Châlons-en-Champagne', N'Grand Est', 0.18) 
	,('FR', N'Chalon-sur-Saône', N'Bourgogne-Franche-Comté', 0.18) 
	,('FR', N'Chambéry', N'Auvergne-Rhône-Alpes', 0.24) 
	,('FR', N'Champigny-sur-Marne', N'Île-de-France', 0.3) 
	,('FR', N'Champs-sur-Marne', N'Île-de-France', 0.1) 
	,('FR', N'Charenton-le-Pont', N'Île-de-France', 0.12) 
	,('FR', N'Charleville-Mézières', N'Grand Est', 0.2) 
	,('FR', N'Chartres', N'Centre-Val de Loire', 0.16) 
	,('FR', N'Châteauroux', N'Centre-Val de Loire', 0.18) 
	,('FR', N'Châtellerault', N'Nouvelle-Aquitaine', 0.13) 
	,('FR', N'Châtenay-Malabry', N'Île-de-France', 0.13) 
	,('FR', N'Châtillon', N'Île-de-France', 0.14) 
	,('FR', N'Chatou', N'Île-de-France', 0.12) 
	,('FR', N'Chaumont', N'Grand Est', 0.09) 
	,('FR', N'Chelles', N'Île-de-France', 0.21) 
	,('FR', N'Cherbourg-Octeville', N'Normandy', 0.15) 
	,('FR', N'Choisy-le-Roi', N'Île-de-France', 0.17) 
	,('FR', N'Cholet', N'Pays de la Loire', 0.22) 
	,('FR', N'Clamart', N'Île-de-France', 0.21) 
	,('FR', N'Clermont-Ferrand', N'Auvergne-Rhône-Alpes', 0.57) 
	,('FR', N'Clichy', N'Île-de-France', 0.24) 
	,('FR', N'Clichy-sous-Bois', N'Île-de-France', 0.12) 
	,('FR', N'Colmar', N'Grand Est', 0.27) 
	,('FR', N'Colombes', N'Île-de-France', 0.34) 
	,('FR', N'Colomiers', N'Occitanie', 0.15) 
	,('FR', N'Combs-la-Ville', N'Île-de-France', 0.09) 
	,('FR', N'Compiègne', N'Hauts-de-France', 0.16) 
	,('FR', N'Conflans-Sainte-Honorine', N'Île-de-France', 0.14) 
	,('FR', N'Corbeil-Essonnes', N'Île-de-France', 0.19) 
	,('FR', N'Cormeilles-en-Parisis', N'Île-de-France', 0.09) 
	,('FR', N'Coudekerque-Branche', N'Hauts-de-France', 0.09) 
	,('FR', N'Courbevoie', N'Île-de-France', 0.34) 
	,('FR', N'Creil', N'Hauts-de-France', 0.14) 
	,('FR', N'Créteil', N'Île-de-France', 0.36) 
	,('FR', N'Croix', N'Hauts-de-France', 0.08) 
	,('FR', N'Dammarie-les-Lys', N'Île-de-France', 0.08) 
	,('FR', N'Dax', N'Nouvelle-Aquitaine', 0.08) 
	,('FR', N'Décines-Charpieu', N'Auvergne-Rhône-Alpes', 0.11) 
	,('FR', N'Denain', N'Hauts-de-France', 0.08) 
	,('FR', N'Deuil-la-Barre', N'Île-de-France', 0.09) 
	,('FR', N'Dieppe', N'Normandy', 0.12) 
	,('FR', N'Dijon', N'Bourgogne-Franche-Comté', 0.61) 
	,('FR', N'Dole', N'Bourgogne-Franche-Comté', 0.09) 
	,('FR', N'Douai', N'Hauts-de-France', 0.17) 
	,('FR', N'Draguignan', N'Provence-Alpes-Côte d''Azur', 0.16) 
	,('FR', N'Drancy', N'Île-de-France', 0.27) 
	,('FR', N'Draveil', N'Île-de-France', 0.12) 
	,('FR', N'Dreux', N'Centre-Val de Loire', 0.13) 
	,('FR', N'Dunkirk', N'Hauts-de-France', 0.36) 
	,('FR', N'Eaubonne', N'Île-de-France', 0.1) 
	,('FR', N'Échirolles', N'Auvergne-Rhône-Alpes', 0.14) 
	,('FR', N'Élancourt', N'Île-de-France', 0.11) 
	,('FR', N'Épernay', N'Grand Est', 0.09) 
	,('FR', N'Épinal', N'Grand Est', 0.13) 
	,('FR', N'Épinay-sur-Seine', N'Île-de-France', 0.22) 
	,('FR', N'Ermont', N'Île-de-France', 0.11) 
	,('FR', N'Étampes', N'Île-de-France', 0.1) 
	,('FR', N'Évreux', N'Normandy', 0.2) 
	,('FR', N'Évry', N'Île-de-France', 0.21) 
	,('FR', N'Fleury-les-Aubrais', N'Centre-Val de Loire', 0.08) 
	,('FR', N'Fontaine', N'Auvergne-Rhône-Alpes', 0.09) 
	,('FR', N'Fontenay-aux-Roses', N'Île-de-France', 0.09) 
	,('FR', N'Fontenay-sous-Bois', N'Île-de-France', 0.21) 
	,('FR', N'Forbach', N'Grand Est', 0.09) 
	,('FR', N'Fort-de-France', N'Martinique', 0.34) 
	,('FR', N'Franconville', N'Île-de-France', 0.13) 
	,('FR', N'Fréjus', N'Provence-Alpes-Côte d''Azur', 0.21) 
	,('FR', N'Fresnes', N'Île-de-France', 0.11) 
	,('FR', N'Frontignan', N'Occitanie', 0.09) 
	,('FR', N'Gagny', N'Île-de-France', 0.16) 
	,('FR', N'Gap', N'Provence-Alpes-Côte d''Azur', 0.16) 
	,('FR', N'Garges-lès-Gonesse', N'Île-de-France', 0.17) 
	,('FR', N'Gennevilliers', N'Île-de-France', 0.17) 
	,('FR', N'Gif-sur-Yvette', N'Île-de-France', 0.08) 
	,('FR', N'Gonesse', N'Île-de-France', 0.1) 
	,('FR', N'Goussainville', N'Île-de-France', 0.13) 
	,('FR', N'Gradignan', N'Nouvelle-Aquitaine', 0.1) 
	,('FR', N'Grande-Synthe', N'Hauts-de-France', 0.09) 
	,('FR', N'Grasse', N'Provence-Alpes-Côte d''Azur', 0.2) 
	,('FR', N'Grenoble', N'Auvergne-Rhône-Alpes', 0.64) 
	,('FR', N'Grigny', N'Île-de-France', 0.11) 
	,('FR', N'Guyancourt', N'Île-de-France', 0.11) 
	,('FR', N'Haguenau', N'Grand Est', 0.14) 
	,('FR', N'Halluin', N'Hauts-de-France', 0.08) 
	,('FR', N'Hazebrouck', N'Hauts-de-France', 0.09) 
	,('FR', N'Hénin-Beaumont', N'Hauts-de-France', 0.11) 
	,('FR', N'Herblay', N'Île-de-France', 0.11) 
	,('FR', N'Hérouville-Saint-Clair', N'Normandy', 0.09) 
	,('FR', N'Houilles', N'Île-de-France', 0.13) 
	,('FR', N'Hyères', N'Provence-Alpes-Côte d''Azur', 0.22) 
	,('FR', N'Illkirch-Graffenstaden', N'Grand Est', 0.11) 
	,('FR', N'Issy-les-Moulineaux', N'Île-de-France', 0.26) 
	,('FR', N'Istres', N'Provence-Alpes-Côte d''Azur', 0.17) 
	,('FR', N'Ivry-sur-Seine', N'Île-de-France', 0.24) 
	,('FR', N'Joué-lès-Tours', N'Centre-Val de Loire', 0.15) 
	,('FR', N'Kourou', N'French Guiana', 0.1) 
	,('FR', N'La Celle-Saint-Cloud', N'Île-de-France', 0.09) 
	,('FR', N'La Ciotat', N'Provence-Alpes-Côte d''Azur', 0.14) 
	,('FR', N'La Courneuve', N'Île-de-France', 0.16) 
	,('FR', N'La Garde', N'Provence-Alpes-Côte d''Azur', 0.1) 
	,('FR', N'La Garenne-Colombes', N'Île-de-France', 0.11) 
	,('FR', N'La Madeleine', N'Hauts-de-France', 0.09) 
	,('FR', N'La Possession', N'Réunion', 0.13) 
	,('FR', N'La Rochelle', N'Nouvelle-Aquitaine', 0.3) 
	,('FR', N'La Roche-sur-Yon', N'Pays de la Loire', 0.21) 
	,('FR', N'La Seyne-sur-Mer', N'Provence-Alpes-Côte d''Azur', 0.26) 
	,('FR', N'La Teste-de-Buch', N'Nouvelle-Aquitaine', 0.1) 
	,('FR', N'La Valette-du-Var', N'Provence-Alpes-Côte d''Azur', 0.09) 
	,('FR', N'Lagny-sur-Marne', N'Île-de-France', 0.08) 
	,('FR', N'Lambersart', N'Hauts-de-France', 0.11) 
	,('FR', N'Lanester', N'Brittany', 0.09) 
	,('FR', N'Laon', N'Hauts-de-France', 0.1) 
	,('FR', N'Laval', N'Pays de la Loire', 0.2) 
	,('FR', N'Le Blanc-Mesnil', N'Île-de-France', 0.21) 
	,('FR', N'Le Bouscat', N'Nouvelle-Aquitaine', 0.09) 
	,('FR', N'Le Cannet', N'Provence-Alpes-Côte d''Azur', 0.17) 
	,('FR', N'Le Chesnay', N'Île-de-France', 0.11) 
	,('FR', N'Le Creusot', N'Bourgogne-Franche-Comté', 0.09) 
	,('FR', N'Le Gosier', N'Guadeloupe', 0.11) 
	,('FR', N'Le Grand-Quevilly', N'Normandy', 0.1) 
	,('FR', N'Le Havre', N'Normandy', 0.69) 
	,('FR', N'Le Kremlin-Bicêtre', N'Île-de-France', 0.1) 
	,('FR', N'Le Lamentin', N'Martinique', 0.16) 
	,('FR', N'Le Mans', N'Pays de la Loire', 0.58) 
	,('FR', N'Le Mée-sur-Seine', N'Île-de-France', 0.08) 
	,('FR', N'Le Moule', N'Guadeloupe', 0.09) 
	,('FR', N'Le Perreux-sur-Marne', N'Île-de-France', 0.13) 
	,('FR', N'Le Petit-Quevilly', N'Normandy', 0.09) 
	,('FR', N'Le Plessis-Robinson', N'Île-de-France', 0.11) 
	,('FR', N'Le Port', N'Réunion', 0.14) 
	,('FR', N'Le Robert', N'Martinique', 0.09) 
	,('FR', N'Le Tampon', N'Réunion', 0.31) 
	,('FR', N'Lens', N'Hauts-de-France', 0.13) 
	,('FR', N'Les Abymes', N'Guadeloupe', 0.23) 
	,('FR', N'Les Lilas', N'Île-de-France', 0.09) 
	,('FR', N'Les Mureaux', N'Île-de-France', 0.13) 
	,('FR', N'Les Pavillons-sous-Bois', N'Île-de-France', 0.09) 
	,('FR', N'Les Ulis', N'Île-de-France', 0.1) 
	,('FR', N'Levallois-Perret', N'Île-de-France', 0.26) 
	,('FR', N'L''Haÿ-les-Roses', N'Île-de-France', 0.13) 
	,('FR', N'Libourne', N'Nouvelle-Aquitaine', 0.1) 
	,('FR', N'Liévin', N'Hauts-de-France', 0.13) 
	,('FR', N'Lille', N'Hauts-de-France', 0.93) 
	,('FR', N'Limoges', N'Nouvelle-Aquitaine', 0.54) 
	,('FR', N'Lisieux', N'Normandy', 0.08) 
	,('FR', N'Livry-Gargan', N'Île-de-France', 0.17) 
	,('FR', N'Longjumeau', N'Île-de-France', 0.09) 
	,('FR', N'Loos', N'Hauts-de-France', 0.08) 
	,('FR', N'Lorient', N'Brittany', 0.23) 
	,('FR', N'Lunel', N'Occitanie', 0.1) 
	,('FR', N'Lyon', N'Auvergne-Rhône-Alpes', 2.01) 
	,('FR', N'Mâcon', N'Bourgogne-Franche-Comté', 0.13) 
	,('FR', N'Maisons-Alfort', N'Île-de-France', 0.22) 
	,('FR', N'Maisons-Laffitte', N'Île-de-France', 0.09) 
	,('FR', N'Malakoff', N'Île-de-France', 0.12) 
	,('FR', N'Mandelieu-la-Napoule', N'Provence-Alpes-Côte d''Azur', 0.09) 
	,('FR', N'Manosque', N'Provence-Alpes-Côte d''Azur', 0.09) 
	,('FR', N'Mantes-la-Jolie', N'Île-de-France', 0.18) 
	,('FR', N'Marcq-en-Barœul', N'Hauts-de-France', 0.15) 
	,('FR', N'Marignane', N'Provence-Alpes-Côte d''Azur', 0.14) 
	,('FR', N'Marseille', N'Provence-Alpes-Côte d''Azur', 3.43) 
	,('FR', N'Martigues', N'Provence-Alpes-Côte d''Azur', 0.19) 
	,('FR', N'Massy', N'Île-de-France', 0.18) 
	,('FR', N'Matoury', N'French Guiana', 0.12) 
	,('FR', N'Maubeuge', N'Hauts-de-France', 0.12) 
	,('FR', N'Meaux', N'Île-de-France', 0.22) 
	,('FR', N'Melun', N'Île-de-France', 0.16) 
	,('FR', N'Menton', N'Provence-Alpes-Côte d''Azur', 0.11) 
	,('FR', N'Mérignac', N'Nouvelle-Aquitaine', 0.27) 
	,('FR', N'Metz', N'Grand Est', 0.48) 
	,('FR', N'Meudon', N'Île-de-France', 0.18) 
	,('FR', N'Meyzieu', N'Auvergne-Rhône-Alpes', 0.13) 
	,('FR', N'Millau', N'Occitanie', 0.09) 
	,('FR', N'Miramas', N'Provence-Alpes-Côte d''Azur', 0.1) 
	,('FR', N'Mons-en-Barœul', N'Hauts-de-France', 0.09) 
	,('FR', N'Montauban', N'Occitanie', 0.23) 
	,('FR', N'Montbéliard', N'Bourgogne-Franche-Comté', 0.1) 
	,('FR', N'Mont-de-Marsan', N'Nouvelle-Aquitaine', 0.13) 
	,('FR', N'Montélimar', N'Auvergne-Rhône-Alpes', 0.15) 
	,('FR', N'Montfermeil', N'Île-de-France', 0.1) 
	,('FR', N'Montgeron', N'Île-de-France', 0.09) 
	,('FR', N'Montigny-le-Bretonneux', N'Île-de-France', 0.13) 
	,('FR', N'Montigny-lès-Metz', N'Grand Est', 0.09) 
	,('FR', N'Montluçon', N'Auvergne-Rhône-Alpes', 0.15) 
	,('FR', N'Montmorency', N'Île-de-France', 0.08) 
	,('FR', N'Montpellier', N'Occitanie', 1.09) 
	,('FR', N'Montreuil', N'Île-de-France', 0.42) 
	,('FR', N'Montrouge', N'Île-de-France', 0.2) 
	,('FR', N'Morsang-sur-Orge', N'Île-de-France', 0.09) 
	,('FR', N'Mulhouse', N'Grand Est', 0.45) 
	,('FR', N'Muret', N'Occitanie', 0.1) 
	,('FR', N'Nancy', N'Grand Est', 0.42) 
	,('FR', N'Nanterre', N'Île-de-France', 0.37) 
	,('FR', N'Nantes', N'Pays de la Loire', 1.17) 
	,('FR', N'Narbonne', N'Occitanie', 0.21) 
	,('FR', N'Neuilly-Plaisance', N'Île-de-France', 0.08) 
	,('FR', N'Neuilly-sur-Marne', N'Île-de-France', 0.14) 
	,('FR', N'Neuilly-sur-Seine', N'Île-de-France', 0.25) 
	,('FR', N'Nevers', N'Bourgogne-Franche-Comté', 0.14) 
	,('FR', N'Nice', N'Provence-Alpes-Côte d''Azur', 1.37) 
	,('FR', N'Nîmes', N'Occitanie', 0.6) 
	,('FR', N'Niort', N'Nouvelle-Aquitaine', 0.23) 
	,('FR', N'Nogent-sur-Marne', N'Île-de-France', 0.13) 
	,('FR', N'Noisy-le-Grand', N'Île-de-France', 0.25) 
	,('FR', N'Noisy-le-Sec', N'Île-de-France', 0.16) 
	,('FR', N'Orange', N'Provence-Alpes-Côte d''Azur', 0.12) 
	,('FR', N'Orléans', N'Centre-Val de Loire', 0.46) 
	,('FR', N'Orly', N'Île-de-France', 0.09) 
	,('FR', N'Orvault', N'Pays de la Loire', 0.1) 
	,('FR', N'Oullins', N'Auvergne-Rhône-Alpes', 0.1) 
	,('FR', N'Oyonnax', N'Auvergne-Rhône-Alpes', 0.09) 
	,('FR', N'Palaiseau', N'Île-de-France', 0.13) 
	,('FR', N'Pantin', N'Île-de-France', 0.21) 
	,('FR', N'Paris', N'Île-de-France', 8.94) 
	,('FR', N'Pau', N'Nouvelle-Aquitaine', 0.31) 
	,('FR', N'Périgueux', N'Nouvelle-Aquitaine', 0.12) 
	,('FR', N'Perpignan', N'Occitanie', 0.49) 
	,('FR', N'Pessac', N'Nouvelle-Aquitaine', 0.24) 
	,('FR', N'Petit-Bourg', N'Guadeloupe', 0.1) 
	,('FR', N'Pierrefitte-sur-Seine', N'Île-de-France', 0.11) 
	,('FR', N'Plaisir', N'Île-de-France', 0.13) 
	,('FR', N'Poissy', N'Île-de-France', 0.15) 
	,('FR', N'Poitiers', N'Nouvelle-Aquitaine', 0.35) 
	,('FR', N'Pontault-Combault', N'Île-de-France', 0.15) 
	,('FR', N'Pontoise', N'Île-de-France', 0.12) 
	,('FR', N'Puteaux', N'Île-de-France', 0.18) 
	,('FR', N'Quimper', N'Brittany', 0.25) 
	,('FR', N'Rambouillet', N'Île-de-France', 0.1) 
	,('FR', N'Reims', N'Grand Est', 0.73) 
	,('FR', N'Rennes', N'Brittany', 0.85) 
	,('FR', N'Rezé', N'Pays de la Loire', 0.16) 
	,('FR', N'Rillieux-la-Pape', N'Auvergne-Rhône-Alpes', 0.12) 
	,('FR', N'Ris-Orangis', N'Île-de-France', 0.11) 
	,('FR', N'Roanne', N'Auvergne-Rhône-Alpes', 0.14) 
	,('FR', N'Rochefort', N'Nouvelle-Aquitaine', 0.1) 
	,('FR', N'Rodez', N'Occitanie', 0.1) 
	,('FR', N'Roissy-en-Brie', N'Île-de-France', 0.09) 
	,('FR', N'Romainville', N'Île-de-France', 0.1) 
	,('FR', N'Romans-sur-Isère', N'Auvergne-Rhône-Alpes', 0.13) 
	,('FR', N'Rosny-sous-Bois', N'Île-de-France', 0.18) 
	,('FR', N'Roubaix', N'Hauts-de-France', 0.38) 
	,('FR', N'Rouen', N'Normandy', 0.44) 
	,('FR', N'Rueil-Malmaison', N'Île-de-France', 0.32) 
	,('FR', N'Saint-André', N'Réunion', 0.23) 
	,('FR', N'Saint-Benoît', N'Réunion', 0.14) 
	,('FR', N'Saint-Brieuc', N'Brittany', 0.18) 
	,('FR', N'Saint-Chamond', N'Auvergne-Rhône-Alpes', 0.14) 
	,('FR', N'Saint-Cloud', N'Île-de-France', 0.12) 
	,('FR', N'Saint-Denis', N'Réunion', 0.57) 
	,('FR', N'Saint-Denis', N'Île-de-France', 0.44) 
	,('FR', N'Saint-Dié-des-Vosges', N'Grand Est', 0.08) 
	,('FR', N'Saint-Dizier', N'Grand Est', 0.1) 
	,('FR', N'Sainte-Anne', N'Guadeloupe', 0.1) 
	,('FR', N'Sainte-Foy-lès-Lyon', N'Auvergne-Rhône-Alpes', 0.09) 
	,('FR', N'Sainte-Geneviève-des-Bois', N'Île-de-France', 0.14) 
	,('FR', N'Sainte-Marie', N'Réunion', 0.13) 
	,('FR', N'Sainte-Rose', N'Guadeloupe', 0.08) 
	,('FR', N'Saintes', N'Nouvelle-Aquitaine', 0.1) 
	,('FR', N'Sainte-Suzanne', N'Réunion', 0.09) 
	,('FR', N'Saint-Étienne', N'Auvergne-Rhône-Alpes', 0.69) 
	,('FR', N'Saint-Étienne-du-Rouvray', N'Normandy', 0.12) 
	,('FR', N'Saint-Genis-Laval', N'Auvergne-Rhône-Alpes', 0.08) 
	,('FR', N'Saint-Germain-en-Laye', N'Île-de-France', 0.16) 
	,('FR', N'Saint-Gratien', N'Île-de-France', 0.08) 
	,('FR', N'Saint-Herblain', N'Pays de la Loire', 0.18) 
	,('FR', N'Saint-Joseph', N'Réunion', 0.15) 
	,('FR', N'Saint-Laurent-du-Maroni', N'French Guiana', 0.17) 
	,('FR', N'Saint-Laurent-du-Var', N'Provence-Alpes-Côte d''Azur', 0.12) 
	,('FR', N'Saint-Leu', N'Réunion', 0.13) 
	,('FR', N'Saint-Louis', N'Réunion', 0.21) 
	,('FR', N'Saint-Malo', N'Brittany', 0.18) 
	,('FR', N'Saint-Mandé', N'Île-de-France', 0.09) 
	,('FR', N'Saint-Martin-d''Hères', N'Auvergne-Rhône-Alpes', 0.15) 
	,('FR', N'Saint-Maur-des-Fossés', N'Île-de-France', 0.3) 
	,('FR', N'Saint-Médard-en-Jalles', N'Nouvelle-Aquitaine', 0.12) 
	,('FR', N'Saint-Michel-sur-Orge', N'Île-de-France', 0.08) 
	,('FR', N'Saint-Nazaire', N'Pays de la Loire', 0.27) 
	,('FR', N'Saint-Ouen', N'Île-de-France', 0.19) 
	,('FR', N'Saint-Ouen-l''Aumône', N'Île-de-France', 0.1) 
	,('FR', N'Saint-Paul', N'Réunion', 0.42) 
	,('FR', N'Saint-Pierre', N'Réunion', 0.33) 
	,('FR', N'Saint-Priest', N'Auvergne-Rhône-Alpes', 0.17) 
	,('FR', N'Saint-Quentin', N'Hauts-de-France', 0.22) 
	,('FR', N'Saint-Raphaël', N'Provence-Alpes-Côte d''Azur', 0.14) 
	,('FR', N'Saint-Sébastien-sur-Loire', N'Pays de la Loire', 0.1) 
	,('FR', N'Salon-de-Provence', N'Provence-Alpes-Côte d''Azur', 0.18) 
	,('FR', N'Sannois', N'Île-de-France', 0.11) 
	,('FR', N'Sarcelles', N'Île-de-France', 0.23) 
	,('FR', N'Sarreguemines', N'Grand Est', 0.09) 
	,('FR', N'Sartrouville', N'Île-de-France', 0.21) 
	,('FR', N'Saumur', N'Pays de la Loire', 0.11) 
	,('FR', N'Savigny-le-Temple', N'Île-de-France', 0.12) 
	,('FR', N'Savigny-sur-Orge', N'Île-de-France', 0.15) 
	,('FR', N'Schiltigheim', N'Grand Est', 0.13) 
	,('FR', N'Sens', N'Bourgogne-Franche-Comté', 0.1) 
	,('FR', N'Sète', N'Occitanie', 0.18) 
	,('FR', N'Sevran', N'Île-de-France', 0.2) 
	,('FR', N'Sèvres', N'Île-de-France', 0.09) 
	,('FR', N'Six-Fours-les-Plages', N'Provence-Alpes-Côte d''Azur', 0.14) 
	,('FR', N'Soissons', N'Hauts-de-France', 0.11) 
	,('FR', N'Sotteville-lès-Rouen', N'Normandy', 0.12) 
	,('FR', N'Stains', N'Île-de-France', 0.15) 
	,('FR', N'Strasbourg', N'Grand Est', 1.11) 
	,('FR', N'Sucy-en-Brie', N'Île-de-France', 0.1) 
	,('FR', N'Suresnes', N'Île-de-France', 0.19) 
	,('FR', N'Talence', N'Nouvelle-Aquitaine', 0.17) 
	,('FR', N'Tarbes', N'Occitanie', 0.16) 
	,('FR', N'Taverny', N'Île-de-France', 0.1) 
	,('FR', N'Thiais', N'Île-de-France', 0.12) 
	,('FR', N'Thionville', N'Grand Est', 0.17) 
	,('FR', N'Thonon-les-Bains', N'Auvergne-Rhône-Alpes', 0.14) 
	,('FR', N'Torcy', N'Île-de-France', 0.09) 
	,('FR', N'Toulon', N'Provence-Alpes-Côte d''Azur', 0.66) 
	,('FR', N'Toulouse', N'Occitanie', 1.84) 
	,('FR', N'Tourcoing', N'Hauts-de-France', 0.38) 
	,('FR', N'Tournefeuille', N'Occitanie', 0.11) 
	,('FR', N'Tours', N'Centre-Val de Loire', 0.54) 
	,('FR', N'Trappes', N'Île-de-France', 0.12) 
	,('FR', N'Tremblay-en-France', N'Île-de-France', 0.14) 
	,('FR', N'Troyes', N'Grand Est', 0.24) 
	,('FR', N'Valence', N'Auvergne-Rhône-Alpes', 0.25) 
	,('FR', N'Valenciennes', N'Hauts-de-France', 0.17) 
	,('FR', N'Vallauris', N'Provence-Alpes-Côte d''Azur', 0.11) 
	,('FR', N'Vandoeuvre-lès-Nancy', N'Grand Est', 0.12) 
	,('FR', N'Vannes', N'Brittany', 0.21) 
	,('FR', N'Vanves', N'Île-de-France', 0.11) 
	,('FR', N'Vaulx-en-Velin', N'Auvergne-Rhône-Alpes', 0.18) 
	,('FR', N'Vélizy-Villacoublay', N'Île-de-France', 0.08) 
	,('FR', N'Vénissieux', N'Auvergne-Rhône-Alpes', 0.25) 
	,('FR', N'Vernon', N'Normandy', 0.1) 
	,('FR', N'Versailles', N'Île-de-France', 0.34) 
	,('FR', N'Vertou', N'Pays de la Loire', 0.09) 
	,('FR', N'Vichy', N'Auvergne-Rhône-Alpes', 0.1) 
	,('FR', N'Vienne', N'Auvergne-Rhône-Alpes', 0.12) 
	,('FR', N'Vierzon', N'Centre-Val de Loire', 0.11) 
	,('FR', N'Vigneux-sur-Seine', N'Île-de-France', 0.12) 
	,('FR', N'Villefranche-sur-Saône', N'Auvergne-Rhône-Alpes', 0.15) 
	,('FR', N'Villejuif', N'Île-de-France', 0.23) 
	,('FR', N'Villemomble', N'Île-de-France', 0.12) 
	,('FR', N'Villenave-d''Ornon', N'Nouvelle-Aquitaine', 0.12) 
	,('FR', N'Villeneuve-d''Ascq', N'Hauts-de-France', 0.25) 
	,('FR', N'Villeneuve-la-Garenne', N'Île-de-France', 0.1) 
	,('FR', N'Villeneuve-Saint-Georges', N'Île-de-France', 0.13) 
	,('FR', N'Villeneuve-sur-Lot', N'Nouvelle-Aquitaine', 0.09) 
	,('FR', N'Villeparisis', N'Île-de-France', 0.1) 
	,('FR', N'Villepinte', N'Île-de-France', 0.14) 
	,('FR', N'Villeurbanne', N'Auvergne-Rhône-Alpes', 0.59) 
	,('FR', N'Villiers-le-Bel', N'Île-de-France', 0.11) 
	,('FR', N'Villiers-sur-Marne', N'Île-de-France', 0.11) 
	,('FR', N'Vincennes', N'Île-de-France', 0.2) 
	,('FR', N'Viry-Châtillon', N'Île-de-France', 0.12) 
	,('FR', N'Vitrolles', N'Provence-Alpes-Côte d''Azur', 0.14) 
	,('FR', N'Vitry-sur-Seine', N'Île-de-France', 0.36) 
	,('FR', N'Wasquehal', N'Hauts-de-France', 0.08) 
	,('FR', N'Wattrelos', N'Hauts-de-France', 0.17) 
	,('FR', N'Yerres', N'Île-de-France', 0.12) 
	,('IN', N'Adoni', N'Andhra Pradesh', 0.08) 
	,('IN', N'Agartala', N'Tripura', 0.2) 
	,('IN', N'Agra', N'Uttar Pradesh', 0.78) 
	,('IN', N'Ahmedabad', N'Gujarat', 2.73) 
	,('IN', N'Ahmednagar', N'Maharashtra', 0.17) 
	,('IN', N'Aizawl', N'Mizoram', 0.14) 
	,('IN', N'Ajmer', N'Rajasthan', 0.27) 
	,('IN', N'Akola', N'Maharashtra', 0.26) 
	,('IN', N'Alappuzha', N'Kerala', 0.09) 
	,('IN', N'Aligarh', N'Uttar Pradesh', 0.44) 
	,('IN', N'Allahabad', N'Uttar Pradesh', 0.55) 
	,('IN', N'Alwar', N'Rajasthan', 0.15) 
	,('IN', N'Amaravati', N'Andhra Pradesh', 0.05) 
	,('IN', N'Ambala', N'Haryana', 0.1) 
	,('IN', N'Ambarnath', N'Maharashtra', 0.12) 
	,('IN', N'Ambattur', N'Tamil Nadu', 0.23) 
	,('IN', N'Amravati', N'Maharashtra', 0.32) 
	,('IN', N'Amritsar', N'Punjab', 0.55) 
	,('IN', N'Amroha', N'Uttar Pradesh', 0.1) 
	,('IN', N'Anand', N'Gujarat', 0.1) 
	,('IN', N'Anantapur', N'Andhra Pradesh', 0.13) 
	,('IN', N'Anantapuram[]', N'Andhra Pradesh', 0.17) 
	,('IN', N'Anantnag', N'Jammu and Kashmir', 0.05) 
	,('IN', N'Arrah', N'Bihar', 0.13) 
	,('IN', N'Asansol', N'West Bengal', 0.28) 
	,('IN', N'Aurangabad', N'Maharashtra', 0.58) 
	,('IN', N'Aurangabad[]', N'Bihar', 0.05) 
	,('IN', N'Avadi', N'Tamil Nadu', 0.17) 
	,('IN', N'Bahraich', N'Uttar Pradesh', 0.09) 
	,('IN', N'Ballia', N'Uttar Pradesh', 0.05) 
	,('IN', N'Bally', N'West Bengal', 0.14) 
	,('IN', N'Bangalore', N'Karnataka', 4.13) 
	,('IN', N'Baranagar', N'West Bengal', 0.12) 
	,('IN', N'Barasat', N'West Bengal', 0.14) 
	,('IN', N'Bardhaman', N'West Bengal', 0.15) 
	,('IN', N'Bareilly', N'Uttar Pradesh', 0.44) 
	,('IN', N'Bathinda', N'Punjab', 0.14) 
	,('IN', N'Begusarai', N'Bihar', 0.12) 
	,('IN', N'Belgaum', N'Karnataka', 0.24) 
	,('IN', N'Bellary', N'Karnataka', 0.2) 
	,('IN', N'Berhampore', N'West Bengal', 0.1) 
	,('IN', N'Berhampur', N'Odisha', 0.17) 
	,('IN', N'Bettiah[]', N'Bihar', 0.07) 
	,('IN', N'Bhagalpur', N'Bihar', 0.2) 
	,('IN', N'Bhalswa Jahangir Pur', N'Delhi', 0.1) 
	,('IN', N'Bharatpur', N'Rajasthan', 0.12) 
	,('IN', N'Bhatpara', N'West Bengal', 0.19) 
	,('IN', N'Bhavnagar', N'Gujarat', 0.29) 
	,('IN', N'Bhilai', N'Chhattisgarh', 0.31) 
	,('IN', N'Bhilwara', N'Rajasthan', 0.18) 
	,('IN', N'Bhimavaram', N'Andhra Pradesh', 0.07) 
	,('IN', N'Bhind', N'Madhya Pradesh', 0.1) 
	,('IN', N'Bhiwandi', N'Maharashtra', 0.35) 
	,('IN', N'Bhiwani', N'Haryana', 0.1) 
	,('IN', N'Bhopal', N'Madhya Pradesh', 0.88) 
	,('IN', N'Bhubaneswar', N'Odisha', 0.41) 
	,('IN', N'Bhusawal', N'Maharashtra', 0.09) 
	,('IN', N'Bidar', N'Karnataka', 0.11) 
	,('IN', N'Bidhannagar', N'West Bengal', 0.11) 
	,('IN', N'Bihar Sharif', N'Bihar', 0.15) 
	,('IN', N'Bijapur', N'Karnataka', 0.16) 
	,('IN', N'Bikaner', N'Rajasthan', 0.32) 
	,('IN', N'Bilaspur', N'Chhattisgarh', 0.16) 
	,('IN', N'Bokaro', N'Jharkhand', 0.2) 
	,('IN', N'Bongaigaon', N'Assam', 0.07) 
	,('IN', N'Budaun', N'Uttar Pradesh', 0.08) 
	,('IN', N'Bulandshahr', N'Uttar Pradesh', 0.11) 
	,('IN', N'Burhanpur', N'Madhya Pradesh', 0.1) 
	,('IN', N'Buxar[]', N'Bihar', 0.05) 
	,('IN', N'Chandigarh', N'Chandigarh', 0.47) 
	,('IN', N'Chandrapur', N'Maharashtra', 0.16) 
	,('IN', N'Chennai', N'Tamil Nadu', 2.29) 
	,('IN', N'Chhapra', N'Bihar', 0.1) 
	,('IN', N'Chinsurah', N'West Bengal', 0.09) 
	,('IN', N'Chittoor[]', N'Andhra Pradesh', 0.09) 
	,('IN', N'Cuttack', N'Odisha', 0.3) 
	,('IN', N'Danapur', N'Bihar', 0.09) 
	,('IN', N'Darbhanga', N'Bihar', 0.14) 
	,('IN', N'Davanagere', N'Karnataka', 0.21) 
	,('IN', N'Dehradun', N'Uttarakhand', 0.28) 
	,('IN', N'Dehri[]', N'Bihar', 0.07) 
	,('IN', N'Delhi', N'Delhi', 5.39) 
	,('IN', N'Deoghar', N'Jharkhand', 0.1) 
	,('IN', N'Dewas', N'Madhya Pradesh', 0.14) 
	,('IN', N'Dhanbad', N'Jharkhand', 0.57) 
	,('IN', N'Dharmavaram', N'Andhra Pradesh', 0.06) 
	,('IN', N'Dhule', N'Maharashtra', 0.18) 
	,('IN', N'Dibrugarh', N'Assam', 0.08) 
	,('IN', N'Dindigul', N'Tamil Nadu', 0.1) 
	,('IN', N'Durg', N'Chhattisgarh', 0.13) 
	,('IN', N'Durgapur', N'West Bengal', 0.28) 
	,('IN', N'Eluru[]', N'Andhra Pradesh', 0.14) 
	,('IN', N'Erode[]', N'Tamil Nadu', 0.24) 
	,('IN', N'Etawah', N'Uttar Pradesh', 0.13) 
	,('IN', N'Faridabad', N'Haryana', 0.69) 
	,('IN', N'Farrukhabad', N'Uttar Pradesh', 0.14) 
	,('IN', N'Fatehpur', N'Uttar Pradesh', 0.09) 
	,('IN', N'Firozabad', N'Uttar Pradesh', 0.3) 
	,('IN', N'Gandhidham', N'Gujarat', 0.12) 
	,('IN', N'Gandhinagar', N'Gujarat', 0.1) 
	,('IN', N'Gangavathi', N'Karnataka', 0.05) 
	,('IN', N'Gangtok', N'Sikkim', 0.05) 
	,('IN', N'Gaya', N'Bihar', 0.23) 
	,('IN', N'Ghaziabad', N'Uttar Pradesh', 0.81) 
	,('IN', N'Giridih', N'Jharkhand', 0.07) 
	,('IN', N'Gopalpur', N'West Bengal', 0.2) 
	,('IN', N'Gorakhpur', N'Uttar Pradesh', 0.33) 
	,('IN', N'Gudivada', N'Andhra Pradesh', 0.06) 
	,('IN', N'Gulbarga', N'Karnataka', 0.26) 
	,('IN', N'Guna', N'Madhya Pradesh', 0.09) 
	,('IN', N'Guntakal', N'Andhra Pradesh', 0.06) 
	,('IN', N'Guntur[]', N'Andhra Pradesh', 0.33) 
	,('IN', N'Gurgaon', N'Haryana', 0.43) 
	,('IN', N'Guwahati', N'Assam', 0.47) 
	,('IN', N'Gwalior', N'Madhya Pradesh', 0.52) 
	,('IN', N'Hajipur[]', N'Bihar', 0.07) 
	,('IN', N'Haldia', N'West Bengal', 0.1) 
	,('IN', N'Hapur', N'Uttar Pradesh', 0.13) 
	,('IN', N'Haridwar', N'Uttarakhand', 0.11) 
	,('IN', N'Hazaribagh', N'Jharkhand', 0.08) 
	,('IN', N'Hindupur', N'Andhra Pradesh', 0.07) 
	,('IN', N'Hospet', N'Karnataka', 0.1) 
	,('IN', N'Hosur', N'Tamil Nadu', 0.06) 
	,('IN', N'Howrah', N'West Bengal', 0.53) 
	,('IN', N'Hubli–Dharwad', N'Karnataka', 0.46) 
	,('IN', N'Hyderabad', N'Telangana', 3.34) 
	,('IN', N'Ichalkaranji', N'Maharashtra', 0.14) 
	,('IN', N'Imphal', N'Manipur', 0.13) 
	,('IN', N'Indore', N'Madhya Pradesh', 0.96) 
	,('IN', N'Jabalpur', N'Madhya Pradesh', 0.52) 
	,('IN', N'Jaipur', N'Rajasthan', 1.49) 
	,('IN', N'Jalandhar', N'Punjab', 0.42) 
	,('IN', N'Jalgaon', N'Maharashtra', 0.39) 
	,('IN', N'Jalna', N'Maharashtra', 0.14) 
	,('IN', N'Jamalpur[]', N'Bihar', 0.05) 
	,('IN', N'Jammu[]', N'Jammu and Kashmir', 0.25) 
	,('IN', N'Jamnagar', N'Gujarat', 0.26) 
	,('IN', N'Jamshedpur', N'Jharkhand', 0.31) 
	,('IN', N'Jaunpur', N'Uttar Pradesh', 0.09) 
	,('IN', N'Jehanabad[]', N'Bihar', 0.05) 
	,('IN', N'Jhansi', N'Uttar Pradesh', 0.25) 
	,('IN', N'Jodhpur', N'Rajasthan', 0.51) 
	,('IN', N'Jorhat', N'Assam', 0.08) 
	,('IN', N'Junagadh', N'Gujarat', 0.16) 
	,('IN', N'Kadapa[]', N'Andhra Pradesh', 0.17) 
	,('IN', N'Kakinada', N'Andhra Pradesh', 0.22) 
	,('IN', N'Kalyan-Dombivli', N'Maharashtra', 0.61) 
	,('IN', N'Kamarhati', N'West Bengal', 0.16) 
	,('IN', N'Kanpur', N'Uttar Pradesh', 1.36) 
	,('IN', N'Karaikudi', N'Tamil Nadu', 0.05) 
	,('IN', N'Karawal Nagar', N'Delhi', 0.11) 
	,('IN', N'Karimnagar', N'Telangana', 0.13) 
	,('IN', N'Karnal', N'Haryana', 0.14) 
	,('IN', N'Karur', N'Tamil Nadu', 0.22) 
	,('IN', N'Katihar', N'Bihar', 0.08) 
	,('IN', N'Katni', N'Madhya Pradesh', 0.11) 
	,('IN', N'Kavali', N'Andhra Pradesh', 0.05) 
	,('IN', N'Khammam', N'Telangana', 0.15) 
	,('IN', N'Khandwa', N'Madhya Pradesh', 0.1) 
	,('IN', N'Kharagpur', N'West Bengal', 0.1) 
	,('IN', N'Kirari Suleman Nagar', N'Delhi', 0.14) 
	,('IN', N'Kishanganj[]', N'Bihar', 0.05) 
	,('IN', N'Kochi', N'Kerala', 0.29) 
	,('IN', N'Kolhapur', N'Maharashtra', 0.27) 
	,('IN', N'Kolkata', N'West Bengal', 2.2) 
	,('IN', N'Kollam', N'Kerala', 0.17) 
	,('IN', N'Korba', N'Chhattisgarh', 0.18) 
	,('IN', N'Kota[]', N'Rajasthan', 0.49) 
	,('IN', N'Kottayam', N'Kerala', 0.08) 
	,('IN', N'Kozhikode', N'Kerala', 0.21) 
	,('IN', N'Kulti', N'West Bengal', 0.15) 
	,('IN', N'Kumbakonam', N'Tamil Nadu', 0.07) 
	,('IN', N'Kurnool[]', N'Andhra Pradesh', 0.24) 
	,('IN', N'Latur', N'Maharashtra', 0.19) 
	,('IN', N'Loni', N'Uttar Pradesh', 0.25) 
	,('IN', N'Lucknow', N'Uttar Pradesh', 1.38) 
	,('IN', N'Ludhiana', N'Punjab', 0.79) 
	,('IN', N'Machilipatnam', N'Andhra Pradesh', 0.08) 
	,('IN', N'Madanapalle', N'Andhra Pradesh', 0.07) 
	,('IN', N'Madhyamgram', N'West Bengal', 0.1) 
	,('IN', N'Madurai', N'Tamil Nadu', 0.5) 
	,('IN', N'Mahbubnagar', N'Telangana', 0.08) 
	,('IN', N'Maheshtala', N'West Bengal', 0.21) 
	,('IN', N'Malda', N'West Bengal', 0.1) 
	,('IN', N'Malegaon', N'Maharashtra', 0.23) 
	,('IN', N'Mangalore', N'Karnataka', 0.24) 
	,('IN', N'Mango', N'Jharkhand', 0.11) 
	,('IN', N'Mathura', N'Uttar Pradesh', 0.17) 
	,('IN', N'Mau', N'Uttar Pradesh', 0.14) 
	,('IN', N'Medininagar', N'Jharkhand', 0.06) 
	,('IN', N'Meerut', N'Uttar Pradesh', 0.64) 
	,('IN', N'Mehsana', N'Gujarat', 0.09) 
	,('IN', N'Midnapore', N'West Bengal', 0.08) 
	,('IN', N'Mira-Bhayandar', N'Maharashtra', 0.4) 
	,('IN', N'Miryalaguda', N'Telangana', 0.05) 
	,('IN', N'Mirzapur', N'Uttar Pradesh', 0.11) 
	,('IN', N'Moradabad', N'Uttar Pradesh', 0.43) 
	,('IN', N'Morbi', N'Gujarat', 0.1) 
	,('IN', N'Morena', N'Madhya Pradesh', 0.1) 
	,('IN', N'Motihari[]', N'Bihar', 0.06) 
	,('IN', N'Mumbai', N'Maharashtra', 6.1) 
	,('IN', N'Munger', N'Bihar', 0.1) 
	,('IN', N'Muzaffarnagar', N'Uttar Pradesh', 0.19) 
	,('IN', N'Muzaffarpur', N'Bihar', 0.17) 
	,('IN', N'Mysore[][][]', N'Karnataka', 0.45) 
	,('IN', N'Nadiad', N'Gujarat', 0.11) 
	,('IN', N'Nagaon', N'Assam', 0.07) 
	,('IN', N'Nagercoil', N'Tamil Nadu', 0.11) 
	,('IN', N'Nagpur', N'Maharashtra', 1.18) 
	,('IN', N'Naihati', N'West Bengal', 0.11) 
	,('IN', N'Nanded', N'Maharashtra', 0.27) 
	,('IN', N'Nandyal', N'Andhra Pradesh', 0.1) 
	,('IN', N'Nangloi Jat', N'Delhi', 0.1) 
	,('IN', N'Narasaraopet', N'Andhra Pradesh', 0.06) 
	,('IN', N'Nashik', N'Maharashtra', 0.73) 
	,('IN', N'Navi Mumbai', N'Maharashtra', 0.55) 
	,('IN', N'Nellore[][]', N'Andhra Pradesh', 0.27) 
	,('IN', N'New Delhi', N'Delhi', 0.12) 
	,('IN', N'Nizamabad', N'Telangana', 0.15) 
	,('IN', N'Noida', N'Uttar Pradesh', 0.31) 
	,('IN', N'North Dumdum', N'West Bengal', 0.12) 
	,('IN', N'Ongole', N'Andhra Pradesh', 0.1) 
	,('IN', N'Orai', N'Uttar Pradesh', 0.09) 
	,('IN', N'Pali', N'Rajasthan', 0.11) 
	,('IN', N'Pallavaram', N'Tamil Nadu', 0.11) 
	,('IN', N'Panchkula', N'Haryana', 0.1) 
	,('IN', N'Panihati', N'West Bengal', 0.19) 
	,('IN', N'Panipat', N'Haryana', 0.14) 
	,('IN', N'Panvel', N'Maharashtra', 0.09) 
	,('IN', N'Parbhani', N'Maharashtra', 0.15) 
	,('IN', N'Patiala', N'Punjab', 0.2) 
	,('IN', N'Patna', N'Bihar', 0.83) 
	,('IN', N'Phagwara', N'Punjab', 0.06) 
	,('IN', N'Phusro', N'Jharkhand', 0.09) 
	,('IN', N'Pimpri-Chinchwad', N'Maharashtra', 0.85) 
	,('IN', N'Pondicherry', N'Puducherry', 0.12) 
	,('IN', N'Port Blair', N'Andaman and Nicobar Islands UT', 0.07) 
	,('IN', N'Proddatur', N'Andhra Pradesh', 0.08) 
	,('IN', N'Pudukkottai', N'Tamil Nadu', 0.06) 
	,('IN', N'Pune', N'Maharashtra', 1.53) 
	,('IN', N'Puri', N'Odisha', 0.1) 
	,('IN', N'Purnia[]', N'Bihar', 0.14) 
	,('IN', N'Raebareli', N'Uttar Pradesh', 0.09) 
	,('IN', N'Raichur', N'Karnataka', 0.11) 
	,('IN', N'Raiganj', N'West Bengal', 0.09) 
	,('IN', N'Raipur', N'Chhattisgarh', 0.49) 
	,('IN', N'Rajahmundry[][]', N'Andhra Pradesh', 0.23) 
	,('IN', N'Rajkot', N'Gujarat', 0.63) 
	,('IN', N'Rajpur Sonarpur', N'West Bengal', 0.21) 
	,('IN', N'Ramagundam[]', N'Telangana', 0.11) 
	,('IN', N'Ramgarh', N'Jharkhand', 0.06) 
	,('IN', N'Rampur', N'Uttar Pradesh', 0.16) 
	,('IN', N'Ranchi', N'Jharkhand', 0.71) 
	,('IN', N'Ratlam', N'Madhya Pradesh', 0.13) 
	,('IN', N'Rewa', N'Madhya Pradesh', 0.12) 
	,('IN', N'Rohtak', N'Haryana', 0.18) 
	,('IN', N'Rourkela', N'Odisha', 0.27) 
	,('IN', N'Sagar', N'Madhya Pradesh', 0.18) 
	,('IN', N'Saharanpur', N'Uttar Pradesh', 0.34) 
	,('IN', N'Saharsa[]', N'Bihar', 0.08) 
	,('IN', N'Salem', N'Tamil Nadu', 0.41) 
	,('IN', N'Sambalpur', N'Odisha', 0.16) 
	,('IN', N'Sambhal', N'Uttar Pradesh', 0.11) 
	,('IN', N'Sangli-Miraj & Kupwad', N'Maharashtra', 0.25) 
	,('IN', N'Sasaram[]', N'Bihar', 0.07) 
	,('IN', N'Satara', N'Maharashtra', 0.16) 
	,('IN', N'Satna', N'Madhya Pradesh', 0.14) 
	,('IN', N'Secunderabad', N'Telangana', 0.11) 
	,('IN', N'Serampore', N'West Bengal', 0.09) 
	,('IN', N'Shahjahanpur', N'Uttar Pradesh', 0.16) 
	,('IN', N'Shimla', N'Himachal Pradesh', 0.08) 
	,('IN', N'Shimoga', N'Karnataka', 0.16) 
	,('IN', N'Shivpuri', N'Madhya Pradesh', 0.09) 
	,('IN', N'Sikar', N'Rajasthan', 0.12) 
	,('IN', N'Silchar', N'Assam', 0.11) 
	,('IN', N'Siliguri', N'West Bengal', 0.25) 
	,('IN', N'Singrauli', N'Madhya Pradesh', 0.11) 
	,('IN', N'Sirsa', N'Haryana', 0.09) 
	,('IN', N'Siwan[]', N'Bihar', 0.07) 
	,('IN', N'Solapur', N'Maharashtra', 0.47) 
	,('IN', N'Sonipat', N'Haryana', 0.14) 
	,('IN', N'South Dumdum', N'West Bengal', 0.2) 
	,('IN', N'Sri Ganganagar', N'Rajasthan', 0.11) 
	,('IN', N'Srikakulam', N'Andhra Pradesh', 0.06) 
	,('IN', N'Srinagar', N'Jammu and Kashmir', 0.58) 
	,('IN', N'Sultan Pur Majra', N'Delhi', 0.09) 
	,('IN', N'Surat', N'Gujarat', 2.19) 
	,('IN', N'Surendranagar Dudhrej', N'Gujarat', 0.09) 
	,('IN', N'Suryapet', N'Telangana', 0.06) 
	,('IN', N'Tadepalligudem', N'Andhra Pradesh', 0.05) 
	,('IN', N'Tadipatri', N'Andhra Pradesh', 0.05) 
	,('IN', N'Tenali', N'Andhra Pradesh', 0.11) 
	,('IN', N'Tezpur', N'Assam', 0.05) 
	,('IN', N'Thane', N'Maharashtra', 0.89) 
	,('IN', N'Thanjavur', N'Tamil Nadu', 0.11) 
	,('IN', N'Thiruvananthapuram', N'Kerala', 0.37) 
	,('IN', N'Thoothukudi', N'Tamil Nadu', 0.12) 
	,('IN', N'Thrissur', N'Kerala', 0.15) 
	,('IN', N'Tinsukia', N'Assam', 0.06) 
	,('IN', N'Tiruchirappalli[]', N'Tamil Nadu', 0.45) 
	,('IN', N'Tirunelveli', N'Tamil Nadu', 0.23) 
	,('IN', N'Tiruppur', N'Tamil Nadu', 0.43) 
	,('IN', N'Tiruvottiyur', N'Tamil Nadu', 0.12) 
	,('IN', N'Tumkur', N'Karnataka', 0.15) 
	,('IN', N'Udaipur', N'Rajasthan', 0.22) 
	,('IN', N'Udupi', N'Karnataka', 0.08) 
	,('IN', N'Ujjain', N'Madhya Pradesh', 0.25) 
	,('IN', N'Ulhasnagar', N'Maharashtra', 0.25) 
	,('IN', N'Uluberia', N'West Bengal', 0.11) 
	,('IN', N'Unnao', N'Uttar Pradesh', 0.09) 
	,('IN', N'Uzhavarkarai', N'Puducherry', 0.15) 
	,('IN', N'Vadodara', N'Gujarat', 0.82) 
	,('IN', N'Varanasi', N'Uttar Pradesh', 0.59) 
	,('IN', N'Vasai-Virar', N'Maharashtra', 0.6) 
	,('IN', N'Vasco Da Gama', N'Goa', 0.05) 
	,('IN', N'Vellore', N'Tamil Nadu', 0.09) 
	,('IN', N'Vijayanagaram', N'Andhra Pradesh', 0.11) 
	,('IN', N'Vijayawada', N'Andhra Pradesh', 0.51) 
	,('IN', N'Visakhapatnam[]', N'Andhra Pradesh', 0.85) 
	,('IN', N'Warangal[][]', N'Telangana', 0.41) 
	,('IN', N'Yamunanagar', N'Haryana', 0.11) 
	,('NL', N'Almere', N'Flevoland', 4.06) 
	,('NL', N'Amersfoort', N'Utrecht', 3.02) 
	,('NL', N'Amsterdam', N'North Holland', 16.74) 
	,('NL', N'Apeldoorn', N'Gelderland', 3.14) 
	,('NL', N'Arnhem', N'Gelderland', 3.09) 
	,('NL', N'Breda', N'North Brabant', 3.54) 
	,('NL', N'Eindhoven', N'North Brabant', 4.49) 
	,('NL', N'Enschede', N'Overijssel', 3.07) 
	,('NL', N'Groningen', N'Groningen', 4.47) 
	,('NL', N'Haarlem', N'North Holland', 3.12) 
	,('NL', N'Haarlemmermeer', N'North Holland', 2.99) 
	,('NL', N'Leiden', N'South Holland', 2.41) 
	,('NL', N'Nijmegen', N'Gelderland', 3.41) 
	,('NL', N'Rotterdam', N'South Holland', 12.48) 
	,('NL', N'''s-Hertogenbosch', N'North Brabant', 2.97) 
	,('NL', N'The Hague', N'South Holland', 10.45) 
	,('NL', N'Tilburg', N'North Brabant', 4.21) 
	,('NL', N'Utrecht', N'Utrecht', 6.85) 
	,('NL', N'Zaanstad', N'North Holland', 3.01) 
	,('NL', N'Zwolle', N'Overijssel', 2.47) 
	,('RU', N'Abakan', N'Siberia', 0.22) 
	,('RU', N'Achinsk', N'Siberia', 0.12) 
	,('RU', N'Aleksin', N'Central', 0.07) 
	,('RU', N'Alexandrov', N'Central', 0.07) 
	,('RU', N'Almetyevsk', N'Volga', 0.18) 
	,('RU', N'Anapa', N'South', 0.11) 
	,('RU', N'Angarsk', N'Siberia', 0.26) 
	,('RU', N'Anzhero-Sudzhensk', N'Siberia', 0.08) 
	,('RU', N'Apatity', N'Northwest', 0.06) 
	,('RU', N'Arkhangelsk', N'Northwest', 0.4) 
	,('RU', N'Armavir', N'South', 0.22) 
	,('RU', N'Arsenyev', N'Far East', 0.06) 
	,('RU', N'Artyom', N'Far East', 0.12) 
	,('RU', N'Arzamas', N'Volga', 0.12) 
	,('RU', N'Asbest', N'Ural', 0.07) 
	,('RU', N'Astrakhan', N'South', 0.61) 
	,('RU', N'Azov', N'South', 0.09) 
	,('RU', N'Balakovo', N'Volga', 0.21) 
	,('RU', N'Balashikha', N'Central', 0.59) 
	,('RU', N'Balashov', N'Volga', 0.09) 
	,('RU', N'Barnaul', N'Siberia', 0.73) 
	,('RU', N'Bataysk', N'South', 0.15) 
	,('RU', N'Belebey', N'Volga', 0.07) 
	,('RU', N'Belgorod', N'Central', 0.45) 
	,('RU', N'Belogorsk', N'Far East', 0.07) 
	,('RU', N'Belorechensk', N'South', 0.06) 
	,('RU', N'Beloretsk', N'Volga', 0.07) 
	,('RU', N'Belovo', N'Siberia', 0.08) 
	,('RU', N'Berdsk', N'Siberia', 0.12) 
	,('RU', N'Berezniki', N'Volga', 0.16) 
	,('RU', N'Beryozovsky', N'Ural', 0.07) 
	,('RU', N'Birobidzhan', N'Far East', 0.08) 
	,('RU', N'Biysk', N'Siberia', 0.23) 
	,('RU', N'Blagoveshchensk', N'Far East', 0.26) 
	,('RU', N'Bor', N'Volga', 0.09) 
	,('RU', N'Borisoglebsk', N'Central', 0.07) 
	,('RU', N'Bratsk', N'Siberia', 0.26) 
	,('RU', N'Bryansk', N'Central', 0.46) 
	,('RU', N'Budyonnovsk', N'North Caucasus', 0.07) 
	,('RU', N'Bugulma', N'Volga', 0.09) 
	,('RU', N'Buynaksk', N'North Caucasus', 0.08) 
	,('RU', N'Buzuluk', N'Volga', 0.1) 
	,('RU', N'Chapayevsk', N'Volga', 0.08) 
	,('RU', N'Chaykovsky', N'Volga', 0.09) 
	,('RU', N'Cheboksary', N'Volga', 0.57) 
	,('RU', N'Chekhov', N'Central', 0.08) 
	,('RU', N'Chelyabinsk', N'Ural', 1.37) 
	,('RU', N'Cherepovets', N'Northwest', 0.36) 
	,('RU', N'Cherkessk', N'North Caucasus', 0.14) 
	,('RU', N'Chernogorsk', N'Siberia', 0.09) 
	,('RU', N'Chistopol', N'Volga', 0.07) 
	,('RU', N'Chita', N'Far East', 0.41) 
	,('RU', N'Derbent', N'North Caucasus', 0.15) 
	,('RU', N'Dimitrovgrad', N'Volga', 0.13) 
	,('RU', N'Dmitrov', N'Central', 0.08) 
	,('RU', N'Dolgoprudny', N'Central', 0.14) 
	,('RU', N'Domodedovo', N'Central', 0.16) 
	,('RU', N'Donskoy', N'Central', 0.07) 
	,('RU', N'Dubna', N'Central', 0.09) 
	,('RU', N'Dzerzhinsk', N'Volga', 0.26) 
	,('RU', N'Dzerzhinsky', N'Central', 0.06) 
	,('RU', N'Elektrostal', N'Central', 0.18) 
	,('RU', N'Elista', N'South', 0.12) 
	,('RU', N'Engels', N'Volga', 0.26) 
	,('RU', N'Feodosia', N'South', 0.08) 
	,('RU', N'Fryazino', N'Central', 0.07) 
	,('RU', N'Gatchina', N'Northwest', 0.1) 
	,('RU', N'Gelendzhik', N'South', 0.09) 
	,('RU', N'Georgiyevsk', N'North Caucasus', 0.08) 
	,('RU', N'Glazov', N'Volga', 0.11) 
	,('RU', N'Gorno-Altaysk', N'Siberia', 0.07) 
	,('RU', N'Grozny', N'North Caucasus', 0.38) 
	,('RU', N'Gubkin', N'Central', 0.1) 
	,('RU', N'Gudermes', N'North Caucasus', 0.07) 
	,('RU', N'Gukovo', N'South', 0.07) 
	,('RU', N'Gus-Khrustalny', N'Central', 0.06) 
	,('RU', N'Irkutsk', N'Siberia', 0.71) 
	,('RU', N'Ishim', N'Ural', 0.07) 
	,('RU', N'Ishimbay', N'Volga', 0.07) 
	,('RU', N'Iskitim', N'Siberia', 0.06) 
	,('RU', N'Ivanovo', N'Central', 0.46) 
	,('RU', N'Ivanteyevka', N'Central', 0.1) 
	,('RU', N'Izberbash', N'North Caucasus', 0.07) 
	,('RU', N'Izhevsk', N'Volga', 0.75) 
	,('RU', N'Kaliningrad', N'Northwest', 0.57) 
	,('RU', N'Kaluga', N'Central', 0.38) 
	,('RU', N'Kamensk-Shakhtinsky', N'South', 0.1) 
	,('RU', N'Kamensk-Uralsky', N'Ural', 0.19) 
	,('RU', N'Kamyshin', N'South', 0.13) 
	,('RU', N'Kansk', N'Siberia', 0.1) 
	,('RU', N'Kaspiysk', N'North Caucasus', 0.15) 
	,('RU', N'Kazan', N'Volga', 1.45) 
	,('RU', N'Kemerovo', N'Siberia', 0.64) 
	,('RU', N'Kerch', N'South', 0.18) 
	,('RU', N'Khabarovsk', N'Far East', 0.71) 
	,('RU', N'Khanty-Mansiysk', N'Ural', 0.12) 
	,('RU', N'Khasavyurt', N'North Caucasus', 0.17) 
	,('RU', N'Khimki', N'Central', 0.3) 
	,('RU', N'Kineshma', N'Central', 0.09) 
	,('RU', N'Kirishi', N'Northwest', 0.06) 
	,('RU', N'Kirov', N'Volga', 0.6) 
	,('RU', N'Kirovo-Chepetsk', N'Volga', 0.08) 
	,('RU', N'Kiselyovsk', N'Siberia', 0.1) 
	,('RU', N'Kislovodsk', N'North Caucasus', 0.15) 
	,('RU', N'Klin', N'Central', 0.09) 
	,('RU', N'Klintsy', N'Central', 0.07) 
	,('RU', N'Kogalym', N'Ural', 0.08) 
	,('RU', N'Kolomna', N'Central', 0.16) 
	,('RU', N'Komsomolsk-on-Amur', N'Far East', 0.28) 
	,('RU', N'Kopeysk', N'Ural', 0.17) 
	,('RU', N'Korolyov', N'Central', 0.26) 
	,('RU', N'Kostroma', N'Central', 0.32) 
	,('RU', N'Kotelniki', N'Central', 0.06) 
	,('RU', N'Kotlas', N'Northwest', 0.07) 
	,('RU', N'Kovrov', N'Central', 0.15) 
	,('RU', N'Krasnodar', N'South', 1.1) 
	,('RU', N'Krasnogorsk', N'Central', 0.2) 
	,('RU', N'Krasnokamensk', N'Far East', 0.06) 
	,('RU', N'Krasnokamsk', N'Volga', 0.06) 
	,('RU', N'Krasnoturyinsk', N'Ural', 0.06) 
	,('RU', N'Krasnoyarsk', N'Siberia', 1.26) 
	,('RU', N'Kropotkin', N'South', 0.09) 
	,('RU', N'Krymsk', N'South', 0.07) 
	,('RU', N'Kstovo', N'Volga', 0.08) 
	,('RU', N'Kumertau', N'Volga', 0.07) 
	,('RU', N'Kungur', N'Volga', 0.07) 
	,('RU', N'Kurgan', N'Ural', 0.36) 
	,('RU', N'Kursk', N'Central', 0.52) 
	,('RU', N'Kuznetsk', N'Volga', 0.09) 
	,('RU', N'Kyzyl', N'Siberia', 0.14) 
	,('RU', N'Labinsk', N'South', 0.07) 
	,('RU', N'Leninogorsk', N'Volga', 0.07) 
	,('RU', N'Leninsk-Kuznetsky', N'Siberia', 0.11) 
	,('RU', N'Lesosibirsk', N'Siberia', 0.07) 
	,('RU', N'Lipetsk', N'Central', 0.58) 
	,('RU', N'Liski', N'Central', 0.06) 
	,('RU', N'Lobnya', N'Central', 0.1) 
	,('RU', N'Lysva', N'Volga', 0.07) 
	,('RU', N'Lytkarino', N'Central', 0.07) 
	,('RU', N'Lyubertsy', N'Central', 0.24) 
	,('RU', N'Magadan', N'Far East', 0.11) 
	,('RU', N'Magnitogorsk', N'Ural', 0.48) 
	,('RU', N'Makhachkala', N'North Caucasus', 0.7) 
	,('RU', N'Maykop', N'South', 0.16) 
	,('RU', N'Meleuz', N'Volga', 0.06) 
	,('RU', N'Mezhdurechensk', N'Siberia', 0.11) 
	,('RU', N'Miass', N'Ural', 0.17) 
	,('RU', N'Michurinsk', N'Central', 0.1) 
	,('RU', N'Mikhaylovka', N'South', 0.07) 
	,('RU', N'Mikhaylovsk', N'North Caucasus', 0.11) 
	,('RU', N'Mineralnye Vody', N'North Caucasus', 0.08) 
	,('RU', N'Minusinsk', N'Siberia', 0.08) 
	,('RU', N'Moscow', N'Central', 14.62) 
	,('RU', N'Murino', N'Northwest', 0.09) 
	,('RU', N'Murmansk', N'Northwest', 0.33) 
	,('RU', N'Murom', N'Central', 0.12) 
	,('RU', N'Mytishchi', N'Central', 0.28) 
	,('RU', N'Naberezhnye Chelny', N'Volga', 0.61) 
	,('RU', N'Nakhodka', N'Far East', 0.16) 
	,('RU', N'Nalchik', N'North Caucasus', 0.28) 
	,('RU', N'Naro-Fominsk', N'Central', 0.08) 
	,('RU', N'Nazran', N'North Caucasus', 0.14) 
	,('RU', N'Neftekamsk', N'Volga', 0.15) 
	,('RU', N'Nefteyugansk', N'Ural', 0.15) 
	,('RU', N'Neryungri', N'Far East', 0.07) 
	,('RU', N'Nevinnomyssk', N'North Caucasus', 0.13) 
	,('RU', N'Nizhnekamsk', N'Volga', 0.28) 
	,('RU', N'Nizhnevartovsk', N'Ural', 0.32) 
	,('RU', N'Nizhny Novgorod', N'Volga', 1.44) 
	,('RU', N'Nizhny Tagil', N'Ural', 0.4) 
	,('RU', N'Noginsk', N'Central', 0.12) 
	,('RU', N'Norilsk', N'Siberia', 0.21) 
	,('RU', N'Novoaltaysk', N'Siberia', 0.09) 
	,('RU', N'Novocheboksarsk', N'Volga', 0.15) 
	,('RU', N'Novocherkassk', N'South', 0.19) 
	,('RU', N'Novokuybyshevsk', N'Volga', 0.11) 
	,('RU', N'Novokuznetsk', N'Siberia', 0.63) 
	,('RU', N'Novomoskovsk', N'Central', 0.14) 
	,('RU', N'Novorossiysk', N'South', 0.32) 
	,('RU', N'Novoshakhtinsk', N'South', 0.12) 
	,('RU', N'Novosibirsk', N'Siberia', 1.87) 
	,('RU', N'Novotroitsk', N'Volga', 0.1) 
	,('RU', N'Novouralsk', N'Ural', 0.09) 
	,('RU', N'Novy Urengoy', N'Ural', 0.14) 
	,('RU', N'Noyabrsk', N'Ural', 0.13) 
	,('RU', N'Nyagan', N'Ural', 0.07) 
	,('RU', N'Obninsk', N'Central', 0.13) 
	,('RU', N'Odintsovo', N'Central', 0.16) 
	,('RU', N'Oktyabrsky', N'Volga', 0.13) 
	,('RU', N'Omsk', N'Siberia', 1.32) 
	,('RU', N'Orekhovo-Zuyevo', N'Central', 0.14) 
	,('RU', N'Orenburg', N'Volga', 0.66) 
	,('RU', N'Orsk', N'Volga', 0.26) 
	,('RU', N'Oryol', N'Central', 0.35) 
	,('RU', N'Ozyorsk', N'Ural', 0.09) 
	,('RU', N'Pavlovo', N'Volga', 0.06) 
	,('RU', N'Pavlovsky Posad', N'Central', 0.07) 
	,('RU', N'Penza', N'Volga', 0.6) 
	,('RU', N'Perm', N'Volga', 1.21) 
	,('RU', N'Pervouralsk', N'Ural', 0.14) 
	,('RU', N'Petropavlovsk-Kamchatsky', N'Far East', 0.21) 
	,('RU', N'Petrozavodsk', N'Northwest', 0.32) 
	,('RU', N'Podolsk', N'Central', 0.36) 
	,('RU', N'Polevskoy', N'Ural', 0.07) 
	,('RU', N'Prokhladny', N'North Caucasus', 0.07) 
	,('RU', N'Prokopyevsk', N'Siberia', 0.22) 
	,('RU', N'Pskov', N'Northwest', 0.24) 
	,('RU', N'Pushkino', N'Central', 0.13) 
	,('RU', N'Pyatigorsk', N'North Caucasus', 0.17) 
	,('RU', N'Ramenskoye', N'Central', 0.14) 
	,('RU', N'Reutov', N'Central', 0.12) 
	,('RU', N'Revda', N'Ural', 0.07) 
	,('RU', N'Rossosh', N'Central', 0.07) 
	,('RU', N'Rostov-on-Don', N'South[]', 1.31) 
	,('RU', N'Rubtsovsk', N'Siberia', 0.16) 
	,('RU', N'Ryazan', N'Central', 0.62) 
	,('RU', N'Rybinsk', N'Central', 0.21) 
	,('RU', N'Rzhev', N'Central', 0.07) 
	,('RU', N'Saint Petersburg', N'Northwest', 6.22) 
	,('RU', N'Salavat', N'Volga', 0.17) 
	,('RU', N'Salekhard', N'Ural', 0.06) 
	,('RU', N'Salsk', N'South', 0.06) 
	,('RU', N'Samara', N'Volga', 1.32) 
	,('RU', N'Saransk', N'Volga', 0.37) 
	,('RU', N'Sarapul', N'Volga', 0.11) 
	,('RU', N'Saratov', N'Volga', 0.96) 
	,('RU', N'Sarov', N'Volga', 0.11) 
	,('RU', N'Sergiyev Posad', N'Central', 0.11) 
	,('RU', N'Serov', N'Ural', 0.11) 
	,('RU', N'Serpukhov', N'Central', 0.14) 
	,('RU', N'Sertolovo', N'Northwest', 0.07) 
	,('RU', N'Sevastopol', N'South', 0.54) 
	,('RU', N'Severodvinsk', N'Northwest', 0.21) 
	,('RU', N'Severomorsk', N'Northwest', 0.06) 
	,('RU', N'Seversk', N'Siberia', 0.12) 
	,('RU', N'Shadrinsk', N'Ural', 0.09) 
	,('RU', N'Shakhty', N'South', 0.26) 
	,('RU', N'Shali', N'North Caucasus', 0.06) 
	,('RU', N'Shchyokino', N'Central', 0.07) 
	,('RU', N'Shchyolkovo', N'Central', 0.15) 
	,('RU', N'Shuya', N'Central', 0.06) 
	,('RU', N'Sibay', N'Volga', 0.07) 
	,('RU', N'Simferopol', N'South', 0.39) 
	,('RU', N'Slavyansk-na-Kubani', N'South', 0.08) 
	,('RU', N'Smolensk', N'Central', 0.37) 
	,('RU', N'Snezhinsk', N'Ural', 0.06) 
	,('RU', N'Sochi', N'South', 0.5) 
	,('RU', N'Solikamsk', N'Volga', 0.11) 
	,('RU', N'Sosnovy Bor', N'Northwest', 0.08) 
	,('RU', N'Stary Oskol', N'Central', 0.26) 
	,('RU', N'Stavropol', N'North Caucasus', 0.53) 
	,('RU', N'Sterlitamak', N'Volga', 0.32) 
	,('RU', N'Stupino', N'Central', 0.08) 
	,('RU', N'Sunzha', N'North Caucasus', 0.08) 
	,('RU', N'Surgut', N'Ural', 0.45) 
	,('RU', N'Svobodny', N'Far East', 0.06) 
	,('RU', N'Syktyvkar', N'Northwest', 0.28) 
	,('RU', N'Syzran', N'Volga', 0.19) 
	,('RU', N'Taganrog', N'South', 0.29) 
	,('RU', N'Tambov', N'Central', 0.33) 
	,('RU', N'Tikhoretsk', N'South', 0.07) 
	,('RU', N'Tikhvin', N'Northwest', 0.07) 
	,('RU', N'Timashyovsk', N'South', 0.06) 
	,('RU', N'Tobolsk', N'Ural', 0.11) 
	,('RU', N'Tolyatti', N'Volga', 0.8) 
	,('RU', N'Tomsk', N'Siberia', 0.66) 
	,('RU', N'Troitsk', N'Ural', 0.08) 
	,('RU', N'Tuapse', N'South', 0.07) 
	,('RU', N'Tula', N'Central', 0.54) 
	,('RU', N'Tuymazy', N'Volga', 0.08) 
	,('RU', N'Tver', N'Central', 0.49) 
	,('RU', N'Tyumen', N'Ural', 0.94) 
	,('RU', N'Ufa', N'Volga', 1.3) 
	,('RU', N'Ukhta', N'Northwest', 0.11) 
	,('RU', N'Ulan-Ude', N'Far East', 0.51) 
	,('RU', N'Ulyanovsk', N'Volga', 0.72) 
	,('RU', N'Urus-Martan', N'North Caucasus', 0.07) 
	,('RU', N'Usolye-Sibirskoye', N'Siberia', 0.09) 
	,('RU', N'Ussuriysk', N'Far East', 0.2) 
	,('RU', N'Ust-Ilimsk', N'Siberia', 0.09) 
	,('RU', N'Velikiye Luki', N'Northwest', 0.1) 
	,('RU', N'Veliky Novgorod', N'Northwest', 0.26) 
	,('RU', N'Verkhnyaya Pyshma', N'Ural', 0.09) 
	,('RU', N'Vidnoye', N'Central', 0.09) 
	,('RU', N'Vladikavkaz', N'North Caucasus', 0.35) 
	,('RU', N'Vladimir', N'Central', 0.41) 
	,('RU', N'Vladivostok', N'Far East', 0.69) 
	,('RU', N'Volgodonsk', N'South', 0.2) 
	,('RU', N'Volgograd', N'South', 1.16) 
	,('RU', N'Vologda', N'Northwest', 0.36) 
	,('RU', N'Volsk', N'Volga', 0.07) 
	,('RU', N'Volzhsk', N'Volga', 0.06) 
	,('RU', N'Volzhsky', N'South', 0.37) 
	,('RU', N'Vorkuta', N'Northwest', 0.06) 
	,('RU', N'Voronezh', N'Central', 1.21) 
	,('RU', N'Voskresensk', N'Central', 0.11) 
	,('RU', N'Votkinsk', N'Volga', 0.11) 
	,('RU', N'Vsevolozhsk', N'Northwest', 0.09) 
	,('RU', N'Vyazma', N'Central', 0.06) 
	,('RU', N'Vyborg', N'Northwest', 0.09) 
	,('RU', N'Vyksa', N'Volga', 0.06) 
	,('RU', N'Yakutsk', N'Far East', 0.38) 
	,('RU', N'Yalta', N'South', 0.09) 
	,('RU', N'Yaroslavl', N'Central', 0.69) 
	,('RU', N'Yegoryevsk', N'Central', 0.08) 
	,('RU', N'Yekaterinburg', N'Ural', 1.73) 
	,('RU', N'Yelabuga', N'Volga', 0.09) 
	,('RU', N'Yelets', N'Central', 0.12) 
	,('RU', N'Yessentuki', N'North Caucasus', 0.13) 
	,('RU', N'Yevpatoria', N'South', 0.12) 
	,('RU', N'Yeysk', N'South', 0.1) 
	,('RU', N'Yoshkar-Ola', N'Volga', 0.32) 
	,('RU', N'Yurga', N'Siberia', 0.09) 
	,('RU', N'Yuzhno-Sakhalinsk', N'Far East', 0.23) 
	,('RU', N'Zarechny', N'Volga', 0.08) 
	,('RU', N'Zelenodolsk', N'Volga', 0.12) 
	,('RU', N'Zelenogorsk', N'Siberia', 0.07) 
	,('RU', N'Zheleznogorsk', N'Central', 0.12) 
	,('RU', N'Zheleznogorsk', N'Siberia', 0.09) 
	,('RU', N'Zhigulyovsk', N'Volga', 0.06) 
	,('RU', N'Zhukovsky', N'Central', 0.12) 
	,('RU', N'Zlatoust', N'Ural', 0.19) 
	,('GB', N'Aldershot', N'Hampshire', 0.97) 
	,('GB', N'Barnsley', N'Yorkshire', 0.84) 
	,('GB', N'Birmingham', N'West Midlands', 9.12) 
	,('GB', N'Blackburn', N'Lancashire', 0.59) 
	,('GB', N'Blackpool', N'Lancashire', 0.56) 
	,('GB', N'Bolton', N'Lancashire', 1.1) 
	,('GB', N'Bournemouth', N'Dorset', 1.52) 
	,('GB', N'Bradford', N'Yorkshire', 1.17) 
	,('GB', N'Brighton and Hove', N'Sussex', 1.09) 
	,('GB', N'Bristol', N'Bristol', 1.7) 
	,('GB', N'Burnley', N'Lancashire', 0.58) 
	,('GB', N'Cambridge', N'Cambridgeshire', 0.52) 
	,('GB', N'Coventry', N'Warwickshire', 1.26) 
	,('GB', N'Crawley', N'Sussex', 0.72) 
	,('GB', N'Derby', N'Derbyshire', 0.99) 
	,('GB', N'Doncaster', N'Yorkshire', 0.51) 
	,('GB', N'Farnborough', N'Hampshire', 0.23) 
	,('GB', N'Gloucester', N'Gloucester', 0.54) 
	,('GB', N'Grimsby', N'Lincolnshire', 0.55) 
	,('GB', N'Hastings', N'Sussex', 0.5) 
	,('GB', N'Huddersfield', N'Yorkshire', 0.58) 
	,('GB', N'Hull', N'Yorkshire', 1.02) 
	,('GB', N'Ipswich', N'Suffolk', 0.72) 
	,('GB', N'Leeds', N'Yorkshire', 2.98) 
	,('GB', N'Leicester', N'Leicestershire', 1.31) 
	,('GB', N'Liverpool', N'Lancashire', 3.3) 
	,('GB', N'London', N'Greater London', 32.97) 
	,('GB', N'Luton', N'Bedfordshire', 0.81) 
	,('GB', N'Manchester', N'Greater Manchester', 6.92) 
	,('GB', N'Mansfield', N'Nottinghamshire', 0.63) 
	,('GB', N'Milton Keynes', N'Buckinghamshire', 0.74) 
	,('GB', N'Newcastle', N'Tyne and Wear', 1.11) 
	,('GB', N'Northampton', N'Northamptonshire', 0.8) 
	,('GB', N'Norwich', N'Norfolk', 0.56) 
	,('GB', N'Nottingham', N'Nottinghamshire', 1.21) 
	,('GB', N'Oxford', N'Oxfordshire', 0.58) 
	,('GB', N'Peterborough', N'Cambridgeshire', 0.54) 
	,('GB', N'Plymouth', N'Devon', 1.02) 
	,('GB', N'Portsmouth', N'Hampshire', 0.82) 
	,('GB', N'Preston', N'Lancashire', 1.0) 
	,('GB', N'Reading', N'Berkshire', 0.62) 
	,('GB', N'Rochdale', N'Lancashire', 0.66) 
	,('GB', N'Sheffield', N'Yorkshire', 2.19) 
	,('GB', N'Southampton', N'Hampshire', 0.95) 
	,('GB', N'Southend-on-Sea', N'Essex', 0.69) 
	,('GB', N'Stoke-on-Trent', N'Staffordshire', 1.43) 
	,('GB', N'Sunderland', N'County Durham', 0.71) 
	,('GB', N'Swindon', N'Wiltshire', 0.62) 
	,('GB', N'Teesside', N'North Yorkshire', 1.88) 
	,('GB', N'Telford', N'Shropshire', 0.55) 
	,('GB', N'Wakefield', N'Yorkshire', 0.58) 
	,('GB', N'Warrington', N'Lancashire', 0.65) 
	,('GB', N'Wigan', N'Lancashire', 0.94) 
	,('GB', N'Wirral', N'Cheshire', 1.32) 
	,('GB', N'Worthing', N'Sussex', 0.73) 
	,('GB', N'York', N'Yorkshire', 0.8) 
	,('US', N'Abilene', N'Texas', 0.13) 
	,('US', N'Akron', N'Ohio', 0.2) 
	,('US', N'Albuquerque', N'New Mexico', 0.58) 
	,('US', N'Alexandria', N'Virginia', 0.16) 
	,('US', N'Allen', N'Texas', 0.11) 
	,('US', N'Allentown', N'Pennsylvania', 0.13) 
	,('US', N'Amarillo', N'Texas', 0.21) 
	,('US', N'Anaheim', N'California', 0.36) 
	,('US', N'Anchorage', N'Alaska', 0.3) 
	,('US', N'Ann Arbor', N'Michigan', 0.13) 
	,('US', N'Antioch', N'California', 0.12) 
	,('US', N'Arlington', N'Texas', 0.41) 
	,('US', N'Arvada', N'Colorado', 0.13) 
	,('US', N'Athens', N'Georgia', 0.13) 
	,('US', N'Atlanta', N'Georgia', 0.51) 
	,('US', N'Augusta', N'Georgia', 0.21) 
	,('US', N'Aurora', N'Colorado', 0.4) 
	,('US', N'Aurora', N'Illinois', 0.19) 
	,('US', N'Austin', N'Texas', 0.99) 
	,('US', N'Bakersfield', N'California', 0.42) 
	,('US', N'Baltimore', N'Maryland', 0.6) 
	,('US', N'Baton Rouge', N'Louisiana', 0.23) 
	,('US', N'Beaumont', N'Texas', 0.12) 
	,('US', N'Bellevue', N'Washington', 0.16) 
	,('US', N'Berkeley', N'California', 0.13) 
	,('US', N'Billings', N'Montana', 0.12) 
	,('US', N'Birmingham', N'Alabama', 0.21) 
	,('US', N'Boise', N'Idaho', 0.24) 
	,('US', N'Boston', N'Massachusetts', 0.7) 
	,('US', N'Boulder', N'Colorado', 0.11) 
	,('US', N'Bridgeport', N'Connecticut', 0.15) 
	,('US', N'Brockton', N'Massachusetts', 0.11) 
	,('US', N'Broken Arrow', N'Oklahoma', 0.12) 
	,('US', N'Brownsville', N'Texas', 0.19) 
	,('US', N'Buffalo', N'New York', 0.29) 
	,('US', N'Burbank', N'California', 0.11) 
	,('US', N'Cambridge', N'Massachusetts', 0.12) 
	,('US', N'Cape Coral', N'Florida', 0.2) 
	,('US', N'Carlsbad', N'California', 0.12) 
	,('US', N'Carrollton', N'Texas', 0.14) 
	,('US', N'Cary', N'North Carolina', 0.18) 
	,('US', N'Cedar Rapids', N'Iowa', 0.14) 
	,('US', N'Centennial', N'Colorado', 0.11) 
	,('US', N'Chandler', N'Arizona', 0.28) 
	,('US', N'Charleston', N'South Carolina', 0.15) 
	,('US', N'Charlotte', N'North Carolina', 0.9) 
	,('US', N'Chattanooga', N'Tennessee', 0.19) 
	,('US', N'Chesapeake', N'Virginia', 0.26) 
	,('US', N'Chicago', N'Illinois', 2.83) 
	,('US', N'Chico', N'California', 0.1) 
	,('US', N'Chula Vista', N'California', 0.28) 
	,('US', N'Cincinnati', N'Ohio', 0.32) 
	,('US', N'Clarksville', N'Tennessee', 0.17) 
	,('US', N'Clearwater', N'Florida', 0.12) 
	,('US', N'Cleveland', N'Ohio', 0.38) 
	,('US', N'Clinton', N'Michigan', 0.1) 
	,('US', N'Clovis', N'California', 0.12) 
	,('US', N'College Station', N'Texas', 0.12) 
	,('US', N'Colorado Springs', N'Colorado', 0.49) 
	,('US', N'Columbia', N'South Carolina', 0.14) 
	,('US', N'Columbia', N'Missouri', 0.13) 
	,('US', N'Columbus', N'Ohio', 0.93) 
	,('US', N'Columbus', N'Georgia', 0.21) 
	,('US', N'Concord', N'California', 0.13) 
	,('US', N'Concord', N'North Carolina', 0.11) 
	,('US', N'Coral Springs', N'Florida', 0.14) 
	,('US', N'Corona', N'California', 0.16) 
	,('US', N'Corpus Christi', N'Texas', 0.33) 
	,('US', N'Costa Mesa', N'California', 0.12) 
	,('US', N'Dallas', N'Texas', 1.34) 
	,('US', N'Daly City', N'California', 0.11) 
	,('US', N'Davenport', N'Iowa', 0.1) 
	,('US', N'Davie', N'Florida', 0.11) 
	,('US', N'Dayton', N'Ohio', 0.14) 
	,('US', N'Dearborn', N'Michigan', 0.11) 
	,('US', N'Denton', N'Texas', 0.14) 
	,('US', N'Denver', N'Colorado', 0.74) 
	,('US', N'Des Moines', N'Iowa', 0.22) 
	,('US', N'Detroit', N'Michigan', 0.66) 
	,('US', N'Downey', N'California', 0.12) 
	,('US', N'Durham', N'North Carolina', 0.29) 
	,('US', N'Edinburg', N'Texas', 0.1) 
	,('US', N'Edison', N'New Jersey', 0.11) 
	,('US', N'El Cajon', N'California', 0.11) 
	,('US', N'El Monte', N'California', 0.11) 
	,('US', N'El Paso', N'Texas', 0.7) 
	,('US', N'Elgin', N'Illinois', 0.12) 
	,('US', N'Elizabeth', N'New Jersey', 0.14) 
	,('US', N'Elk Grove', N'California', 0.18) 
	,('US', N'Escondido', N'California', 0.16) 
	,('US', N'Eugene', N'Oregon', 0.18) 
	,('US', N'Evansville', N'Indiana', 0.12) 
	,('US', N'Everett', N'Washington', 0.11) 
	,('US', N'Fairfield', N'California', 0.12) 
	,('US', N'Fargo', N'North Dakota', 0.13) 
	,('US', N'Fayetteville', N'North Carolina', 0.21) 
	,('US', N'Federal Way', N'Washington', 0.1) 
	,('US', N'Fontana', N'California', 0.21) 
	,('US', N'Fort Collins', N'Colorado', 0.17) 
	,('US', N'Fort Lauderdale', N'Florida', 0.19) 
	,('US', N'Fort Wayne', N'Indiana', 0.27) 
	,('US', N'Fort Worth', N'Texas', 0.95) 
	,('US', N'Fremont', N'California', 0.24) 
	,('US', N'Fresno', N'California', 0.56) 
	,('US', N'Frisco', N'Texas', 0.21) 
	,('US', N'Fullerton', N'California', 0.15) 
	,('US', N'Gainesville', N'Florida', 0.15) 
	,('US', N'Garden Grove', N'California', 0.18) 
	,('US', N'Garland', N'Texas', 0.25) 
	,('US', N'Gilbert', N'Arizona', 0.28) 
	,('US', N'Glendale', N'Arizona', 0.26) 
	,('US', N'Glendale', N'California', 0.2) 
	,('US', N'Grand Prairie', N'Texas', 0.2) 
	,('US', N'Grand Rapids', N'Michigan', 0.2) 
	,('US', N'Greeley', N'Colorado', 0.11) 
	,('US', N'Green Bay', N'Wisconsin', 0.11) 
	,('US', N'Greensboro', N'North Carolina', 0.31) 
	,('US', N'Gresham', N'Oregon', 0.12) 
	,('US', N'Hampton', N'Virginia', 0.14) 
	,('US', N'Hartford', N'Connecticut', 0.12) 
	,('US', N'Hayward', N'California', 0.17) 
	,('US', N'Henderson', N'Nevada', 0.33) 
	,('US', N'Hialeah', N'Florida', 0.23) 
	,('US', N'High Point', N'North Carolina', 0.12) 
	,('US', N'Hillsboro', N'Oregon', 0.11) 
	,('US', N'Hollywood', N'Florida', 0.16) 
	,('US', N'Honolulu', N'Hawaii', 0.36) 
	,('US', N'Houston', N'Texas', 2.37) 
	,('US', N'Huntington Beach', N'California', 0.2) 
	,('US', N'Huntsville', N'Alabama', 0.22) 
	,('US', N'Independence', N'Missouri', 0.13) 
	,('US', N'Indianapolis', N'Indiana', 0.91) 
	,('US', N'Inglewood', N'California', 0.11) 
	,('US', N'Irvine', N'California', 0.32) 
	,('US', N'Irving', N'Texas', 0.26) 
	,('US', N'Jackson', N'Mississippi', 0.16) 
	,('US', N'Jacksonville', N'Florida', 0.98) 
	,('US', N'Jersey City', N'New Jersey', 0.3) 
	,('US', N'Joliet', N'Illinois', 0.15) 
	,('US', N'Jurupa Valley', N'California', 0.11) 
	,('US', N'Kansas City', N'Missouri', 0.52) 
	,('US', N'Kansas City', N'Kansas', 0.16) 
	,('US', N'Kent', N'Washington', 0.14) 
	,('US', N'Killeen', N'Texas', 0.16) 
	,('US', N'Knoxville', N'Tennessee', 0.2) 
	,('US', N'Lafayette', N'Louisiana', 0.13) 
	,('US', N'Lakeland', N'Florida', 0.12) 
	,('US', N'Lakewood', N'Colorado', 0.16) 
	,('US', N'Lakewood', N'New Jersey', 0.14) 
	,('US', N'Lancaster', N'California', 0.18) 
	,('US', N'Lansing', N'Michigan', 0.12) 
	,('US', N'Laredo', N'Texas', 0.26) 
	,('US', N'Las Cruces', N'New Mexico', 0.11) 
	,('US', N'Las Vegas', N'Nevada', 0.66) 
	,('US', N'League City', N'Texas', 0.12) 
	,('US', N'Lee''s Summit', N'Missouri', 0.1) 
	,('US', N'Lewisville', N'Texas', 0.12) 
	,('US', N'Lexington', N'Kentucky', 0.33) 
	,('US', N'Lincoln', N'Nebraska', 0.3) 
	,('US', N'Little Rock', N'Arkansas', 0.21) 
	,('US', N'Long Beach', N'California', 0.48) 
	,('US', N'Los Angeles', N'California', 4.02) 
	,('US', N'Louisville', N'Kentucky', 0.65) 
	,('US', N'Lowell', N'Massachusetts', 0.12) 
	,('US', N'Lubbock', N'Texas', 0.26) 
	,('US', N'Lynn', N'Massachusetts', 0.1) 
	,('US', N'Macon', N'Georgia', 0.16) 
	,('US', N'Madison', N'Wisconsin', 0.28) 
	,('US', N'Manchester', N'New Hampshire', 0.12) 
	,('US', N'McAllen', N'Texas', 0.15) 
	,('US', N'McKinney', N'Texas', 0.2) 
	,('US', N'Memphis', N'Tennessee', 0.65) 
	,('US', N'Menifee', N'California', 0.11) 
	,('US', N'Meridian', N'Idaho', 0.12) 
	,('US', N'Mesa', N'Arizona', 0.52) 
	,('US', N'Mesquite', N'Texas', 0.15) 
	,('US', N'Miami', N'Florida', 0.46) 
	,('US', N'Miami Gardens', N'Florida', 0.12) 
	,('US', N'Midland', N'Texas', 0.14) 
	,('US', N'Milwaukee', N'Wisconsin', 0.59) 
	,('US', N'Minneapolis', N'Minnesota', 0.44) 
	,('US', N'Miramar', N'Florida', 0.14) 
	,('US', N'Mobile', N'Alabama', 0.19) 
	,('US', N'Modesto', N'California', 0.23) 
	,('US', N'Montgomery', N'Alabama', 0.21) 
	,('US', N'Moreno Valley', N'California', 0.21) 
	,('US', N'Murfreesboro', N'Tennessee', 0.16) 
	,('US', N'Murrieta', N'California', 0.11) 
	,('US', N'Nampa', N'Idaho', 0.1) 
	,('US', N'Naperville', N'Illinois', 0.15) 
	,('US', N'Nashville', N'Tennessee', 0.71) 
	,('US', N'New Bedford', N'Massachusetts', 0.1) 
	,('US', N'New Haven', N'Connecticut', 0.14) 
	,('US', N'New Orleans', N'Louisiana', 0.4) 
	,('US', N'New York', N'New York', 9.07) 
	,('US', N'Newark', N'New Jersey', 0.32) 
	,('US', N'Newport News', N'Virginia', 0.19) 
	,('US', N'Norfolk', N'Virginia', 0.25) 
	,('US', N'Norman', N'Oklahoma', 0.13) 
	,('US', N'North Charleston', N'South Carolina', 0.12) 
	,('US', N'North Las Vegas', N'Nevada', 0.27) 
	,('US', N'Norwalk', N'California', 0.11) 
	,('US', N'Oakland', N'California', 0.45) 
	,('US', N'Oceanside', N'California', 0.18) 
	,('US', N'Odessa', N'Texas', 0.12) 
	,('US', N'Oklahoma City', N'Oklahoma', 0.7) 
	,('US', N'Olathe', N'Kansas', 0.15) 
	,('US', N'Omaha', N'Nebraska', 0.5) 
	,('US', N'Ontario', N'California', 0.18) 
	,('US', N'Orange', N'California', 0.14) 
	,('US', N'Orlando', N'Florida', 0.32) 
	,('US', N'Overland Park', N'Kansas', 0.2) 
	,('US', N'Oxnard', N'California', 0.21) 
	,('US', N'Palm Bay', N'Florida', 0.12) 
	,('US', N'Palmdale', N'California', 0.17) 
	,('US', N'Pasadena', N'Texas', 0.16) 
	,('US', N'Pasadena', N'California', 0.14) 
	,('US', N'Paterson', N'New Jersey', 0.16) 
	,('US', N'Pearland', N'Texas', 0.13) 
	,('US', N'Pembroke Pines', N'Florida', 0.18) 
	,('US', N'Peoria', N'Arizona', 0.2) 
	,('US', N'Peoria', N'Illinois', 0.12) 
	,('US', N'Philadelphia', N'Pennsylvania', 1.65) 
	,('US', N'Phoenix', N'Arizona', 1.66) 
	,('US', N'Pittsburgh', N'Pennsylvania', 0.31) 
	,('US', N'Plano', N'Texas', 0.29) 
	,('US', N'Pomona', N'California', 0.16) 
	,('US', N'Pompano Beach', N'Florida', 0.12) 
	,('US', N'Port St. Lucie', N'Florida', 0.21) 
	,('US', N'Portland', N'Oregon', 0.67) 
	,('US', N'Providence', N'Rhode Island', 0.2) 
	,('US', N'Provo', N'Utah', 0.12) 
	,('US', N'Pueblo', N'Colorado', 0.12) 
	,('US', N'Quincy', N'Massachusetts', 0.1) 
	,('US', N'Raleigh', N'North Carolina', 0.48) 
	,('US', N'Rancho Cucamonga', N'California', 0.18) 
	,('US', N'Reno', N'Nevada', 0.27) 
	,('US', N'Renton', N'Washington', 0.11) 
	,('US', N'Rialto', N'California', 0.11) 
	,('US', N'Richardson', N'Texas', 0.12) 
	,('US', N'Richmond', N'Virginia', 0.23) 
	,('US', N'Richmond', N'California', 0.12) 
	,('US', N'Rio Rancho', N'New Mexico', 0.11) 
	,('US', N'Riverside', N'California', 0.32) 
	,('US', N'Roanoke', N'Virginia', 0.1) 
	,('US', N'Rochester', N'New York', 0.22) 
	,('US', N'Rochester', N'Minnesota', 0.13) 
	,('US', N'Rockford', N'Illinois', 0.15) 
	,('US', N'Roseville', N'California', 0.15) 
	,('US', N'Round Rock', N'Texas', 0.12) 
	,('US', N'Sacramento', N'California', 0.54) 
	,('US', N'Saint Paul', N'Minnesota', 0.32) 
	,('US', N'Salem', N'Oregon', 0.18) 
	,('US', N'Salinas', N'California', 0.17) 
	,('US', N'Salt Lake City', N'Utah', 0.21) 
	,('US', N'San Antonio', N'Texas', 1.48) 
	,('US', N'San Bernardino', N'California', 0.23) 
	,('US', N'San Diego', N'California', 1.43) 
	,('US', N'San Francisco', N'California', 0.9) 
	,('US', N'San Jose', N'California', 1.04) 
	,('US', N'San Mateo', N'California', 0.11) 
	,('US', N'Sandy Springs', N'Georgia', 0.11) 
	,('US', N'Santa Ana', N'California', 0.32) 
	,('US', N'Santa Clara', N'California', 0.13) 
	,('US', N'Santa Clarita', N'California', 0.24) 
	,('US', N'Santa Maria', N'California', 0.11) 
	,('US', N'Santa Rosa', N'California', 0.18) 
	,('US', N'Savannah', N'Georgia', 0.15) 
	,('US', N'Scottsdale', N'Arizona', 0.25) 
	,('US', N'Seattle', N'Washington', 0.76) 
	,('US', N'Shreveport', N'Louisiana', 0.19) 
	,('US', N'Simi Valley', N'California', 0.13) 
	,('US', N'Sioux Falls', N'South Dakota', 0.2) 
	,('US', N'South Bend', N'Indiana', 0.11) 
	,('US', N'South Fulton', N'Georgia', 0.11) 
	,('US', N'Sparks', N'Nevada', 0.11) 
	,('US', N'Spokane', N'Washington', 0.24) 
	,('US', N'Spokane Valley', N'Washington', 0.11) 
	,('US', N'Springfield', N'Missouri', 0.17) 
	,('US', N'Springfield', N'Massachusetts', 0.16) 
	,('US', N'Springfield', N'Illinois', 0.12) 
	,('US', N'St. Louis', N'Missouri', 0.31) 
	,('US', N'St. Petersburg', N'Florida', 0.27) 
	,('US', N'Stamford', N'Connecticut', 0.14) 
	,('US', N'Sterling Heights', N'Michigan', 0.14) 
	,('US', N'Stockton', N'California', 0.33) 
	,('US', N'Sugar Land', N'Texas', 0.11) 
	,('US', N'Sunnyvale', N'California', 0.16) 
	,('US', N'Surprise', N'Arizona', 0.15) 
	,('US', N'Syracuse', N'New York', 0.15) 
	,('US', N'Tacoma', N'Washington', 0.23) 
	,('US', N'Tallahassee', N'Florida', 0.2) 
	,('US', N'Tampa', N'Florida', 0.4) 
	,('US', N'Temecula', N'California', 0.11) 
	,('US', N'Tempe', N'Arizona', 0.19) 
	,('US', N'Thornton', N'Colorado', 0.15) 
	,('US', N'Thousand Oaks', N'California', 0.13) 
	,('US', N'Toledo', N'Ohio', 0.28) 
	,('US', N'Topeka', N'Kansas', 0.13) 
	,('US', N'Torrance', N'California', 0.15) 
	,('US', N'Tucson', N'Arizona', 0.56) 
	,('US', N'Tulsa', N'Oklahoma', 0.43) 
	,('US', N'Tyler', N'Texas', 0.11) 
	,('US', N'Vacaville', N'California', 0.11) 
	,('US', N'Vallejo', N'California', 0.13) 
	,('US', N'Vancouver', N'Washington', 0.2) 
	,('US', N'Ventura', N'California', 0.11) 
	,('US', N'Victorville', N'California', 0.14) 
	,('US', N'Virginia Beach', N'Virginia', 0.47) 
	,('US', N'Visalia', N'California', 0.15) 
	,('US', N'Waco', N'Texas', 0.14) 
	,('US', N'Warren', N'Michigan', 0.14) 
	,('US', N'Washington', N'District of Columbia', 0.71) 
	,('US', N'Waterbury', N'Connecticut', 0.12) 
	,('US', N'West Covina', N'California', 0.11) 
	,('US', N'West Jordan', N'Utah', 0.12) 
	,('US', N'West Palm Beach', N'Florida', 0.12) 
	,('US', N'West Valley City', N'Utah', 0.14) 
	,('US', N'Westminster', N'Colorado', 0.12) 
	,('US', N'Wichita', N'Kansas', 0.41) 
	,('US', N'Wichita Falls', N'Texas', 0.11) 
	,('US', N'Wilmington', N'North Carolina', 0.12) 
	,('US', N'Winston–Salem', N'North Carolina', 0.26) 
	,('US', N'Woodbridge', N'New Jersey', 0.11) 
	,('US', N'Worcester', N'Massachusetts', 0.21) 
	,('US', N'Yonkers', N'New York', 0.22) 
) 
AS [source] ([COUNTRY_CODE], [NAME], [PROVINCE], [POPULATION_PERCENT]) 
ON 
	[target].[L_COUNTRY_CODE] = [source].[COUNTRY_CODE] AND 
	[target].[L_PROVINCE] = [source].[PROVINCE]  AND
	[target].[L_NAME] = [source].[NAME]
	

WHEN NOT MATCHED BY TARGET THEN 
	 INSERT ([L_COUNTRY_CODE], [L_PROVINCE], [L_NAME], [L_POPULATION_PERCENT]) 
	 VALUES ([source].[COUNTRY_CODE], [source].[PROVINCE], [source].[NAME], [source].[POPULATION_PERCENT]) 

WHEN MATCHED THEN 
	UPDATE SET [L_POPULATION_PERCENT] = [source].[POPULATION_PERCENT];

PRINT N'Defragmenting [dimensions].[LOCATION] indexes ...';
EXECUTE[utils].[DEFRAG_TABLE_INDEXES] @limit = 1.0, @tableName = N'[dimensions].[LOCATION]';
